/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-30 16:53:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.contract;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.common.DateFormatUtil;
import com.gt.s.kos.contract.vo.GtContractVO;
import com.gt.s.common.CodeUtil;

public final class contractSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.common.DateFormatUtil");
    _jspx_imports_classes.add("com.gt.s.kos.contract.vo.GtContractVO");
    _jspx_imports_classes.add("com.gt.s.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	GtContractVO cvo = (GtContractVO)request.getAttribute("cvo");
	String app = cvo.getApprover();
	String count = cvo.getCount();
	String s = CodeUtil.edsmjeoncheck(app, Integer.parseInt(count));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>기안서(계약) page</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("<script src=\"resources/js/common.js\"></script>\r\n");
      out.write("<script src=\"resources/js/common.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				var app = '");
      out.print(cvo.getApprover());
      out.write("';\r\n");
      out.write("				var dept = '");
      out.print(cvo.getDept());
      out.write("';\r\n");
      out.write("				var pro = '");
      out.print(cvo.getProval());
      out.write("';\r\n");
      out.write("				var appcount = '");
      out.print(cvo.getCount());
      out.write("';\r\n");
      out.write("				var s = '");
      out.print(s);
      out.write("';\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				var app_ = app.split(\"/\");\r\n");
      out.write("				var dept_ = dept.split(\"/\");\r\n");
      out.write("				\r\n");
      out.write("				if(pro != 'null') {\r\n");
      out.write("					var pro_ = pro.split(\"/\");\r\n");
      out.write("				}else {\r\n");
      out.write("					var pro_ = \"\";\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				var write = '");
      out.print(cvo.getWriter());
      out.write("'\r\n");
      out.write("				var insertdate = '");
      out.print(cvo.getInsertdate());
      out.write("'\r\n");
      out.write("				var reference = '");
      out.print(cvo.getReference());
      out.write("'\r\n");
      out.write("				var subject = '");
      out.print(cvo.getGcsubject());
      out.write("'\r\n");
      out.write("				var salplace = '");
      out.print(cvo.getGcsalplace());
      out.write("'\r\n");
      out.write("				var purchase = '");
      out.print(cvo.getGcpurchase());
      out.write("'\r\n");
      out.write("				var content = '");
      out.print(cvo.getGccontent());
      out.write("'\r\n");
      out.write("				var conform = '");
      out.print(cvo.getGcconform());
      out.write('\'');
      out.write(' ');
      out.write("\r\n");
      out.write("				var salitem = '");
      out.print(cvo.getGcsalitem());
      out.write('\'');
      out.write('	');
      out.write(' ');
      out.write("\r\n");
      out.write("				var salquantity = '");
      out.print(cvo.getGcsalquantity());
      out.write('\'');
      out.write(' ');
      out.write("\r\n");
      out.write("				var salamount = '");
      out.print(cvo.getGcsalamount());
      out.write('\'');
      out.write('	');
      out.write("\r\n");
      out.write("				var sign = '");
      out.print(cvo.getGcsign());
      out.write("'\r\n");
      out.write("				\r\n");
      out.write("				/* saltable */\r\n");
      out.write("				var salitem_ = salitem.split(\",\");\r\n");
      out.write("				var salquantity_ = salquantity.split(\",\");\r\n");
      out.write("				var salamount_ = salamount.split(\",\");\r\n");
      out.write("					for (var i= 0; i < salitem_.length-1; i++){\r\n");
      out.write("						$(\"#saltable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(1)\").text(salitem_[i]);\r\n");
      out.write("						$(\"#saltable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(2)\").text(salquantity_[i]);\r\n");
      out.write("						$(\"#saltable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(3)\").text(salamount_[i]);\r\n");
      out.write("					}\r\n");
      out.write("				var puritem = '");
      out.print(cvo.getGcpuritem());
      out.write('\'');
      out.write(' ');
      out.write("\r\n");
      out.write("				var puramount = '");
      out.print(cvo.getGcpuramount());
      out.write('\'');
      out.write('	');
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				/* purtable */\r\n");
      out.write("				var puritem_ = puritem.split(\",\");\r\n");
      out.write("				var puramount_ = puramount.split(\",\");\r\n");
      out.write("			\r\n");
      out.write("					for (var i= 0; i < puritem_.length-1; i++){\r\n");
      out.write("						if(puritem_[i] != \"\"){\r\n");
      out.write("						$(\"#purtable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(1)\").text(purchase);\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#purtable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(2)\").text(puritem_[i]);\r\n");
      out.write("						$(\"#purtable\").find(\"tr:eq(\"+(i+2)+\")\").find(\"td:eq(3)\").text(puramount_[i]);\r\n");
      out.write("					}\r\n");
      out.write("				\r\n");
      out.write("				var attach = '");
      out.print(cvo.getGcattach());
      out.write("'\r\n");
      out.write("				var sign = '");
      out.print(cvo.getGcsign());
      out.write('\'');
      out.write(' ');
      out.write("\r\n");
      out.write("				var file = '");
      out.print(cvo.getGcfile());
      out.write("'\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + file);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + write);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + insertdate);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + reference);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + subject);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + salplace);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + purchase);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + content);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + conform);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + salitem);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + salquantity);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + salamount);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + puritem);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + puramount);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + sign);\r\n");
      out.write("					console.log(\">>>>>>>>>>>>>>>>>>>>>>>>> \" + attach);\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("					\r\n");
      out.write("				console.log(\"s > : \" + s);\r\n");
      out.write("				if(appcount < 0) {\r\n");
      out.write("					var nappcount = Number(appcount) + 10;\r\n");
      out.write("					for(var i=0; i<app_.length; i++) {\r\n");
      out.write("						if(app_[i] != \"-\"){\r\n");
      out.write("							if(app_[i] != \"-\"){\r\n");
      out.write("							 $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("			 				 $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("		                     if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("		                        $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("		                     }\r\n");
      out.write("		                  }\r\n");
      out.write("		                  if(nappcount == i) {\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("		                     if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("		                        $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"반려\");\r\n");
      out.write("		                     }\r\n");
      out.write("		                  }\r\n");
      out.write("\r\n");
      out.write("		               }\r\n");
      out.write("		            }\r\n");
      out.write("		         }else {\r\n");
      out.write("		        	 \r\n");
      out.write("		         }\r\n");
      out.write("				\r\n");
      out.write("		         if(s != '') {\r\n");
      out.write("		            for(var i=0; i<app_.length; i++) {\r\n");
      out.write("		               if(app_[i] != \"-\"){\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(appcount-9)+\")\").find(\"td:eq(5)\").text(pro_[0]);\r\n");
      out.write("		                  if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"전결\");\r\n");
      out.write("		                  }\r\n");
      out.write("		               }\r\n");
      out.write("		            }\r\n");
      out.write("		         }else {\r\n");
      out.write("		            for(var i=0; i<app_.length; i++) {\r\n");
      out.write("		               if(app_[i] != \"-\"){\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("		                  $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("		                  if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("		                     $(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("		                  }\r\n");
      out.write("		               }\r\n");
      out.write("		            }\r\n");
      out.write("		         }\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				// 매출\r\n");
      out.write("				 var price = 0;\r\n");
      out.write("				 \r\n");
      out.write("				for (var i= 0; i < salquantity_.length; i++){\r\n");
      out.write("					price += (Number(salquantity_[i]) * Number(salamount_[i]));\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				console.log(price);\r\n");
      out.write("				\r\n");
      out.write("	        	var aa = (Math.floor(price/10)*10); // 소계\r\n");
      out.write("	        	\r\n");
      out.write("	        	var d = (Math.floor((price/10)/10)*10); // 부가세\r\n");
      out.write("	        	var e = comma(d.toString()); //계산 후에 콤마 붙이기\r\n");
      out.write("	        	\r\n");
      out.write("	        	var f = aa + d;// 합계\r\n");
      out.write("	        	\r\n");
      out.write("				$(\"#totalprice_1\").text(comma(aa.toString()) + \"원\");\r\n");
      out.write("	        	$(\"#totalprice_2\").text(e + \"원\");\r\n");
      out.write("	        	$(\"#totalprice_3\").text(comma(f) + \"원\");\r\n");
      out.write("				\r\n");
      out.write("	        	\r\n");
      out.write("	        	// 매입\r\n");
      out.write("	        	var price_ = 0;\r\n");
      out.write("	        	\r\n");
      out.write("	        	for (var i= 0; i < puramount_.length; i++){\r\n");
      out.write("	    			price_ += Number(puramount_[i]);\r\n");
      out.write("				}\r\n");
      out.write("	        	\r\n");
      out.write("	        	console.log(\">>>>> \" + price_);\r\n");
      out.write("	        	\r\n");
      out.write("	        	$(\"#totalprice_4\").text(comma(price_.toString()) + \"원\");\r\n");
      out.write("	        	\r\n");
      out.write("	          	$(\"#totalprice_5\").text(comma(f) + \"원\"); //매출값\r\n");
      out.write("	        	$(\"#totalprice_6\").text(comma(price_.toString()) + \"원\"); //매입값\r\n");
      out.write("	        	\r\n");
      out.write("	        	var ftotal = f - price_; //이익값\r\n");
      out.write("	        	$(\"#totalprice_7\").text(comma(ftotal)+ \"원\");\r\n");
      out.write("	        	\r\n");
      out.write("	        	\r\n");
      out.write("	        	// 체크박스 - 계약형태\r\n");
      out.write("	    		console.log(conform);				\r\n");
      out.write("	    		var conform_ = conform.replace(\",\",\"\");\r\n");
      out.write("	    		console.log(conform_);				\r\n");
      out.write("	    			\r\n");
      out.write("    			$(\".gcconform\").each(function(){\r\n");
      out.write("    				if($(this).val() == conform_){\r\n");
      out.write("    					$(this).prop(\"checked\", true);\r\n");
      out.write("    				}\r\n");
      out.write("    			});\r\n");
      out.write("	 \r\n");
      out.write("    			// 체크박스 - 동의사안\r\n");
      out.write("	    		console.log(sign);\r\n");
      out.write("    			\r\n");
      out.write("    			$(\".gcsign\").each(function(){\r\n");
      out.write("    				if($(this).val() == sign){\r\n");
      out.write("    					$(this).prop(\"checked\", true);\r\n");
      out.write("    				}\r\n");
      out.write("    			});\r\n");
      out.write("    			\r\n");
      out.write("    			\r\n");
      out.write("				var num = '");
      out.print(cvo.getGcnum() );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"gcfileDownloadlist.gos\",\r\n");
      out.write("					type:\"GET\",\r\n");
      out.write("					data:{\"gcnum\":num},\r\n");
      out.write("					success:whens\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				function whens(d) {\r\n");
      out.write("					var filename = d.split(\",\");\r\n");
      out.write("					for(var i=0; i<filename.length-1; i++) {\r\n");
      out.write("						$(\"#table3\").find(\"tr:eq(0)\").find(\"td:eq(0)\").append(\"<a href='gcfileDownload?file=\"+filename[i]+\"&num=\"+num+\"' target='_blank'>\"+filename[i]+\"</a><br>\");\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".button-container {\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".initial-size {\r\n");
      out.write("	min-height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	background-color: #f2f2f2; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#approval {\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"approval\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../approvalline/select.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<form id=\"gcform\">\r\n");
      out.write("		<div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"button-container\">\r\n");
      out.write("			<button type=\"button\" id=\"line12\">결재선지정</button>\r\n");
      out.write("			<button type=\"button\" id=\"sbtn\">상신</button>\r\n");
      out.write("			<button type=\"button\" id=\"cbtn\">취소</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<h2 align=\"center\">기안서(계약건)</h2>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">문서번호</th>\r\n");
      out.write("				<td width=\"230px\">");
      out.print(cvo.getGcnum() );
      out.write("</td>\r\n");
      out.write("				<th width=\"120px\">보안구분</th>\r\n");
      out.write("				<td width=\"230px\">비공개</td>\r\n");
      out.write("				<!--  채번 -->\r\n");
      out.write("				<th width=\"120px\">보존연한</th>\r\n");
      out.write("				<td width=\"230px\">5년</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"100px\">작성자</th>\r\n");
      out.write("				<td width=\"230px\" id=\"writer1\">");
      out.print(cvo.getWriter() );
      out.write("</td>\r\n");
      out.write("				<!-- 작성자 -->\r\n");
      out.write("				<th width=\"120px\">작성일자</th>\r\n");
      out.write("				<td width=\"230px\" id=\"writeday\" colspan=\"3\">");
      out.print(cvo.getInsertdate() );
      out.write("</td>\r\n");
      out.write("				<!-- 작성일자 -->\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table style=\"text-align: center\" id=\"table1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"5%\">순서</th>\r\n");
      out.write("				<th width=\"8%\">구분</th>\r\n");
      out.write("				<th width=\"17%\">결재자</th>\r\n");
      out.write("				<th width=\"17%\">부서</th>\r\n");
      out.write("				<th width=\"8%\">상태</th>\r\n");
      out.write("				<th width=\"10%\">결재일</th>\r\n");
      out.write("				<th width=\"35%\">결재의견</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">1</td>\r\n");
      out.write("				<td id=\"snag1\"></td>\r\n");
      out.write("				<td id=\"hu1\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept1\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">2</td>\r\n");
      out.write("				<td id=\"snag2\"></td>\r\n");
      out.write("				<td id=\"hu2\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept2\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">3</td>\r\n");
      out.write("				<td id=\"snag3\"></td>\r\n");
      out.write("				<td id=\"hu3\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept3\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">4</td>\r\n");
      out.write("				<td id=\"snag4\"></td>\r\n");
      out.write("				<td id=\"hu4\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept4\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">5</td>\r\n");
      out.write("				<td id=\"snag5\"></td>\r\n");
      out.write("				<td id=\"hu5\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept5\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table id=\"cham1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("            ");
 if(cvo.getReference() == null) {
            	cvo.setReference(" ");
            } 
      out.write("\r\n");
      out.write("				<th width=\"15%\">참 조</th>\r\n");
      out.write("				<td id=\"cham\">");
      out.print(cvo.getReference() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<!-- 제목 -->\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"15%\">제 목</th>\r\n");
      out.write("				<td>");
      out.print(cvo.getGcsubject());
      out.write("</td>\r\n");
      out.write("				<!-- 제목 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br> \r\n");
      out.write("		\r\n");
      out.write("		<table>\r\n");
      out.write("			<!-- 매출, 매입, 계약, 계약형태 -->\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"15%\">1. 매 출 처</th>\r\n");
      out.write("				<td>");
      out.print(cvo.getGcsalplace());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"15%\">2. 매 입 처</th>\r\n");
      out.write("				<td>");
      out.print(cvo.getGcpurchase());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"15%\">3. 계약(매출)내용</th>\r\n");
      out.write("				<td>");
      out.print(cvo.getGccontent());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"133px\">계 약 형 태</th>\r\n");
      out.write("				<td style=\"text-align:left;\">\r\n");
      out.write("					<input type=\"checkbox\" class=\"gcconform\" name=\"gcconform\" id=\"gcconform\" value=\"0\">구매 \r\n");
      out.write("					<input type=\"checkbox\" class=\"gcconform\" name=\"gcconform\" id=\"gcconform\" value=\"1\">계약 \r\n");
      out.write("					<input type=\"checkbox\" class=\"gcconform\" name=\"gcconform\" id=\"gcconform\" value=\"2\">매출 \r\n");
      out.write("					<input type=\"checkbox\" class=\"gcconform\" name=\"gcconform\" id=\"gcconform\" value=\"3\">입찰\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<!-- 매출 계산 -->\r\n");
      out.write("		<table id=\"saltable\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"4\">매출</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th></th>\r\n");
      out.write("				<th>품목</th>\r\n");
      out.write("				<th>수량</th>\r\n");
      out.write("				<th>금액</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 수량 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 수량 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("			</tr>			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 수량 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>\r\n");
      out.write("					<!-- 소계 칸 -->\r\n");
      out.write("				<td colspan=\"1\"\r\n");
      out.write("					style='text-align: center; background-color: #f2f2f2; font-weight: bold;'\r\n");
      out.write("					width=\"200px\">소 계</td>\r\n");
      out.write("				<td colspan=\"2\" width=\"80px\" style=\"text-align: right;\"\r\n");
      out.write("					id=\"totalprice_1\"></td>\r\n");
      out.write("				</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>\r\n");
      out.write("					<!-- 부가세 칸 -->\r\n");
      out.write("				<td colspan=\"1\"\r\n");
      out.write("					style='text-align: center; background-color: #f2f2f2; font-weight: bold;'\r\n");
      out.write("					width=\"200px\">부 가 세</td>\r\n");
      out.write("				<td colspan=\"2\" width=\"80px\" style=\"text-align: right;\"\r\n");
      out.write("					id=\"totalprice_2\"></td>\r\n");
      out.write("				</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>\r\n");
      out.write("					<!-- 합계 칸 -->\r\n");
      out.write("				<td colspan=\"1\" style='text-align: center; background-color: #f2f2f2; font-weight: bold;' width=\"200px\">합 계</td>\r\n");
      out.write("				<td colspan=\"2\" width=\"80px\" style=\"text-align: right;\" id=\"totalprice_3\"></td>\r\n");
      out.write("				</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<!-- 매입 계산 -->\r\n");
      out.write("		<table id=\"purtable\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"5\">매입</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th></th>\r\n");
      out.write("				<th>매입처</th>\r\n");
      out.write("				<th>품목</th>\r\n");
      out.write("				<th>금액</th>\r\n");
      out.write("				<th>비고</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 매입처 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("				<td align=\"center\">-</td>\r\n");
      out.write("				<!-- 비교 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 매입처 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("				<td align=\"center\">-</td>\r\n");
      out.write("				<!-- 비교 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\"></td>\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 매입처 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 품목 -->\r\n");
      out.write("				<td align=\"center\"></td>\r\n");
      out.write("				<!-- 금액 -->\r\n");
      out.write("				<td align=\"center\">-</td>\r\n");
      out.write("				<!-- 비교 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>\r\n");
      out.write("					<!-- 합계 칸 -->\r\n");
      out.write("				<td colspan=\"2\"\r\n");
      out.write("					style='text-align: center; background-color: #f2f2f2; font-weight: bold;'\r\n");
      out.write("					width=\"200px\">합 계</td>\r\n");
      out.write("				<td colspan=\"2\" width=\"80px\" style=\"text-align: right;\"\r\n");
      out.write("					id=\"totalprice_4\"></td>\r\n");
      out.write("				</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<!-- 매출이익 계산 -->\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"2\" style=\"width: 500px\">매출이익</th>\r\n");
      out.write("				<th colspan=\"1\" style=\"width: 500px\">비고</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"1\" width=\"20%\">매 출</th>\r\n");
      out.write("				<td style=\"text-align: right;\" id=\"totalprice_5\"></td>\r\n");
      out.write("				<td rowspan=\"3\">-</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"1\" width=\"20%\">매 입</th>\r\n");
      out.write("				<td style=\"text-align: right;\" id=\"totalprice_6\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"1\" width=\"20%\">이 익</th>\r\n");
      out.write("				<td style=\"text-align: right;\" id=\"totalprice_7\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 계약서 첨부 칸 -->\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"20%\">첨 부 서</th>\r\n");
      out.write("				<td>");
      out.print(cvo.getGcattach());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<th width=\"20%\">대표이사 동의 사안</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div style=\"text-align:left;\">\r\n");
      out.write("						<input type=\"checkbox\" class=\"gcsign\" name=\"gcsign\" id=\"gcsign\" value=\"0\" checked>사용인감 날인 \r\n");
      out.write("						<input type=\"checkbox\" class=\"gcsign\" name=\"gcsign\" id=\"gcsign\" value=\"1\">법인인감 날인\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</th>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<!-- 첨부파일 -->\r\n");
      out.write("	<form id=\"fileform\">\r\n");
      out.write("		<table id=\"table3\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"20%\">첨 부 파 일</th>\r\n");
      out.write("				<td class=\"left-align\" style='text-align: left;'></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div class=\"button-container\" >\r\n");
      out.write("			<button type=\"button\" id=\"line12\">결재선지정</button>\r\n");
      out.write("			<button type=\"button\" id=\"sbtn\">상신</button>\r\n");
      out.write("			<button type=\"button\" id=\"cbtn\">취소</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
