/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 07:43:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accountSelectForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("	<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$(\"#search\").keyup(function () {\r\n");
      out.write("			          var key = $(\"#search\").val();\r\n");
      out.write("					  \r\n");
      out.write("			          $.ajax({\r\n");
      out.write("			            url: \"AccountSelectForm2.gos\",\r\n");
      out.write("			            data: { ganame: key },\r\n");
      out.write("			            success: function (data) {\r\n");
      out.write("			            	 \r\n");
      out.write("			              var row = data.split(\"/\");\r\n");
      out.write("			              console.log(row);\r\n");
      out.write("			              for (var i = 0; i < row.length - 1; i++) {\r\n");
      out.write("			                var list = row[i].split(\",\");\r\n");
      out.write("			                \r\n");
      out.write("			                $(\"#ganum\").val(list[0]);\r\n");
      out.write("			                $(\"#ganame\").val(list[1]);\r\n");
      out.write("			                $(\"#gasnum\").val(list[2]);\r\n");
      out.write(" 			                $(\"#gabusinesstype\").val(list[3]);\r\n");
      out.write("			                $(\"#gaevent\").val(list[4]);\r\n");
      out.write("			                $(\"#gazone\").val(list[5]);\r\n");
      out.write("			                $(\"#gaload\").val(list[6]);\r\n");
      out.write(" 			                $(\"#galoaddetale\").val(list[7]);\r\n");
      out.write("			                $(\"#gahp\").val(list[8]);\r\n");
      out.write("			                $(\"#gafax\").val(list[9]);\r\n");
      out.write(" 			                $(\"#gafoundation\").val(list[10]);\r\n");
      out.write("			                $(\"#startdate\").val(list[11]);\r\n");
      out.write("			                $(\"#enddate\").val(list[12]);\r\n");
      out.write("			                $(\"#gagubun\").val(list[13]);\r\n");
      out.write("			                $(\"#gainfo\").text(list[14]);\r\n");
      out.write("			                \r\n");
      out.write("			               \r\n");
      out.write("			                \r\n");
      out.write("			              }\r\n");
      out.write("			            },\r\n");
      out.write("			          });\r\n");
      out.write("  \r\n");
      out.write("					    \r\n");
      out.write("			        });\r\n");
      out.write("				\r\n");
      out.write("				$(document).on(\"click\", \"#regbtn\", function () {\r\n");
      out.write("			          \r\n");
      out.write("			          //시작일 종료일 계약처 이름을 보내야함\r\n");
      out.write("			          \r\n");
      out.write("			          \r\n");
      out.write("				     var start = document.getElementById(\"startdate\").value;\r\n");
      out.write("				     var end = document.getElementById(\"enddate\").value;	\r\n");
      out.write("				     var ganame = document.getElementById(\"ganame\").value;\r\n");
      out.write("				     var ganum = document.getElementById(\"ganum\").value;\r\n");
      out.write("				     \r\n");
      out.write("				     \r\n");
      out.write("				     \r\n");
      out.write("				  		window.opener.popaccount(start, end , ganame, ganum);\r\n");
      out.write("				  		window.close();\r\n");
      out.write("			        });\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}); // end of ready\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("/* 		input[type=date]::-webkit-datetime-edit-text { */\r\n");
      out.write("/* 		    -webkit-appearance: none; */\r\n");
      out.write("/* 		    display: none; */\r\n");
      out.write("/* 		} */\r\n");
      out.write("/* 		input[type=date]::-webkit-datetime-edit-month-field{ */\r\n");
      out.write("/* 		    -webkit-appearance: none; */\r\n");
      out.write("/* 		    display: none; */\r\n");
      out.write("/* 		} */\r\n");
      out.write("/* 		input[type=date]::-webkit-datetime-edit-day-field { */\r\n");
      out.write("/* 		    -webkit-appearance: none; */\r\n");
      out.write("/* 		    display: none; */\r\n");
      out.write("/* 		} */\r\n");
      out.write("/* 		input[type=date]::-webkit-datetime-edit-year-field { */\r\n");
      out.write("/* 		    -webkit-appearance: none; */\r\n");
      out.write("/* 		    display: none; */\r\n");
      out.write("/* 		} */\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</style>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		  $(document).on('input','#asd',function(){\r\n");
      out.write("        	 $(\"#asd\").css(\"display\",\"inline\");\r\n");
      out.write("    	  });\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<form name=\"accountInsert\" id=\"accountInsert\">\r\n");
      out.write("		<h3>업체 등록</h3>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr><td>거래처 검색<input type=\"text\" id=\"search\" name=\"search\" ></td></tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>거래처코드</td>\r\n");
      out.write("				<td colspan=\"50\">거래처명</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" name=\"ganum\" id=\"ganum\" readonly></td>\r\n");
      out.write("				<td colspan=\"50\"><input type=\"text\" name=\"ganame\" id=\"ganame\" style=\"colspan:3; width:351px;\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>사업자번호</td>\r\n");
      out.write("				<td>업태</td>\r\n");
      out.write("				<td>종목</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" name=\"gasnum\" id=\"gasnum\" readonly></td>\r\n");
      out.write("				<td><input type=\"text\" name=\"gabusinesstype\" id=\"gabusinesstype\" readonly></td>\r\n");
      out.write("				<td><input type=\"text\" name=\"gaevent\" id=\"gaevent\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>우편번호</td>\r\n");
      out.write("				<td>주소</td>\r\n");
      out.write("				<td>상세주소</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" name=\"gazone\" id=\"gazone\" readonly></td>\r\n");
      out.write("				<td><input type=\"text\" name=\"gaload\" id=\"gaload\" readonly></td>\r\n");
      out.write("				<td><input type=\"text\" name=\"galoaddetale\" id=\"galoaddetale\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>전화번호</td>\r\n");
      out.write("				<td>FAX</td>\r\n");
      out.write("				<td>창립일</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" name=\"gahp\" id=\"gahp\" readonly></td>\r\n");
      out.write("				<td><input type=\"text\" name=\"gafax\" id=\"gafax\" readonly></td>\r\n");
      out.write("				<td><input type=\"date\" style=\"width:172px;\" name=\"gafoundation\" id=\"gafoundation\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>거래 시작일</td>\r\n");
      out.write("				<td>거래 종료일</td>\r\n");
      out.write("				<td>사용구분</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"date\" style=\"width:172px;\" name=\"startdate\" id=\"startdate\" readonly></td>\r\n");
      out.write("				<td><input type=\"date\" style=\"width:172px;\" name=\"enddate\" id=\"enddate\" readonly></td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<select name=\"gagubun\" id=\"gagubun\" style=\"width:177px; height:21px;\" readonly>\r\n");
      out.write("						    <option value=\"Y\">예</option>\r\n");
      out.write("		    				<option value=\"N\">아니오</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>설명</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td colspan=\"50\"><textarea id=\"gainfo\" name=\"gainfo\" rows=\"15\" style=\"width:534px;\" readonly></textarea></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div style=\"float:right\">\r\n");
      out.write("			<button type=\"reset\">취소</button>\r\n");
      out.write("			<button id=\"regbtn\">등록</button>\r\n");
      out.write("			<button>삭제</button>	\r\n");
      out.write("		</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
