/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 07:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainSide_002dbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>GOAT.S</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://webfontworld.github.io/kopus/KoPubWorldDotum.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/mainSide-bar.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("                \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("         \r\n");
      out.write("    	  $(document).on(\"click\", \"#noti_click_\", function(){\r\n");
      out.write("    		  var gename = $(\"#gename\").text();\r\n");
      out.write("    		  var url=\"http://192.168.0.35:5000/session/\"+gename;\r\n");
      out.write("    		  window.open(url, \"_blank\", \"width=780,height=650\");\r\n");
      out.write("    	  });\r\n");
      out.write("    	  \r\n");
      out.write("         $(\"#1\").hover(function(){\r\n");
      out.write("             $(\"#project\").css({\"visibility\":\"visible\",\"position\":\"static\"});\r\n");
      out.write("           }, function(){\r\n");
      out.write("             $(\"#project\").css({\"visibility\":\"hidden\",\"position\":\"fixed\"});\r\n");
      out.write("           });\r\n");
      out.write("         \r\n");
      out.write("        $(\"#2\").hover(function(){\r\n");
      out.write("          $(\"#appdiv\").css({\"visibility\":\"visible\",\"position\":\"static\"});\r\n");
      out.write("        }, function(){\r\n");
      out.write("          $(\"#appdiv\").css({\"visibility\":\"hidden\",\"position\":\"fixed\"});\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        $(\".myLink\").on(\"click\", function() {\r\n");
      out.write("            window.location.href = \"mainpage_draft2.gos\";\r\n");
      out.write("          });\r\n");
      out.write("      \r\n");
      out.write("          \r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url:\"logincheck.gos\",\r\n");
      out.write("           async:false,\r\n");
      out.write("           success:gename,\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("       function gename(d){\r\n");
      out.write("          if(d != \"loginx\"){\r\n");
      out.write("             $(\"#gename\").text(d);\r\n");
      out.write("             if(d == \"admin\") {\r\n");
      out.write("            	 $(\".side_img\").append(\"<li class='toggle-event'><a class='top-menu'><img src='resources/goats_icon/admin.png'><span class='arrow'>관리자</span></a>\"\r\n");
      out.write("											+\"<ul class='toggle-menu'>\"\r\n");
      out.write("											+	\"<li><a href='gtAdminSelectAll.gos'><img\"\r\n");
      out.write("											+			\"src='resources/goats_icon/hyphen.png'><span>사원 정보 수정</span></a></li>\"\r\n");
      out.write("											+	\"<li><a href='employeeInsertForm.gos'><img\"\r\n");
      out.write("											+			\"src='resources/goats_icon/hyphen.png'><span>회원가입\"\r\n");
      out.write("											+				\"</span></a></li>\"\r\n");
      out.write("											+\"</ul></li>\");\r\n");
      out.write("             }\r\n");
      out.write("          }else{\r\n");
      out.write("             location.href=\"loginx.gos\"\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       $(document).on(\"click\", \".nav-logo\", function(){\r\n");
      out.write("    	   location.href=\"mainpage.gos\";\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("	  	$(document).on(\"click\", \".nav-profile\", function(){\r\n");
      out.write("		location.href=\"gtMypageSelect.gos\";\r\n");
      out.write("		});\r\n");
      out.write("       \r\n");
      out.write("       $.ajax({\r\n");
      out.write("          url:\"gtsidebarcheck.gos\",\r\n");
      out.write("          async:false,\r\n");
      out.write("          success:appcheck\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("      function appcheck(d) {\r\n");
      out.write("         if(d == \"OK\") {\r\n");
      out.write("            $(\".app\").css({\"color\":\"red\"});\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("       \r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       $(function(){\r\n");
      out.write("\r\n");
      out.write("         $(\".toggle-event\").click(function(){\r\n");
      out.write("            $(this).find(\".toggle-menu\").toggleClass(\"active\");\r\n");
      out.write("            $(this).find(\".arrow\").toggleClass(\"active-arrow\");\r\n");
      out.write("            $(this).find(\".top-menu\").toggleClass(\"top-menu-active\");\r\n");
      out.write("          })\r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'KoPubWorldDotum';\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      out.write("	<!-- 사이드바 -->\r\n");
      out.write("	<nav class=\"navWrap\">\r\n");
      out.write("		<!-- 사이드바 로고  -->\r\n");
      out.write("		<div class=\"nav-logo\">\r\n");
      out.write("			<img src=\"resources/goats_icon/logo.png\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 사이드바 로고  -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 사이드바 프로필-->\r\n");
      out.write("		<div class=\"nav-profile\">\r\n");
      out.write("			<img src=\"resources/goats_icon/my.png\"> <span id=\"gename\"></span>님\r\n");
      out.write("			반갑습니다.\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 사이드바 프로필-->\r\n");
      out.write("\r\n");
      out.write("		<!-- 사이드바 메뉴 리스트 -->\r\n");
      out.write("		<div class=\"nav-menuWrap\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<div class=\"side_img\">\r\n");
      out.write("					<li><a class=\"top-menu\" href=\"mainpage.gos\"><img\r\n");
      out.write("							src=\"resources/goats_icon/home.png\"><span>Home</span></a></li>\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"top-menu\" href=\"gtBusinessSelectAll.gos\"><img\r\n");
      out.write("							src=\"resources/goats_icon/bisiness.png\"><span>출장</span></a></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"toggle-event\"><a class=\"top-menu\"><img\r\n");
      out.write("							src=\"resources/goats_icon/vacation.png\"><span class=\"arrow\">휴가</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul class=\"toggle-menu\">\r\n");
      out.write("							<li><a href=\"gtVacationSelect_.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>휴가 현황</span></a></li>\r\n");
      out.write("							<li><a href=\"gtVacationSelectAll.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>전체 휴가\r\n");
      out.write("										현황</span></a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"toggle-event\"><a class=\"top-menu\"><img\r\n");
      out.write("							src=\"resources/goats_icon/project.png\"><span class=\"arrow\">프로젝트</span></a>\r\n");
      out.write("						<ul class=\"toggle-menu\">\r\n");
      out.write("							<li><a href=\"ProjectSelectAll.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>프로젝트\r\n");
      out.write("										관리</span></a></li>\r\n");
      out.write("							<li><a href=\"projectactualcost.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>실비 관리</span></a></li>\r\n");
      out.write("							<li><a href=\"accountSelectAll.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>거래처 관리</span></a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"top-menu\" href=\"#\" id=\"noti_click_\"><img\r\n");
      out.write("							src=\"resources/goats_icon/board.png\"><span>공지사항</span></a></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"toggle-event\">\r\n");
      out.write("						<!-- <a class=\"top-menu\" onclick=\"location.href='document.gos';\"><img src=\"resources/goats_icon/write.png\"><span class=\"arrow\">전자결재</span></a> -->\r\n");
      out.write("						<a class=\"top-menu\"><img src=\"resources/goats_icon/EDSM.png\"><span\r\n");
      out.write("							class=\"arrow app\">전자결재</span></a>\r\n");
      out.write("						<ul class=\"toggle-menu\">\r\n");
      out.write("							<li><a href=\"document.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>문서함</span></a></li>\r\n");
      out.write("							<li><a href=\"document_approve.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>결재함</span></a></li>\r\n");
      out.write("							<li><a href=\"document_prog.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>진행함</span></a></li>\r\n");
      out.write("							<li><a href=\"document_ref.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>참조함</span></a></li>\r\n");
      out.write("							<li><a href=\"document_com.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>기안함</span></a></li>\r\n");
      out.write("							<li><a href=\"document_napp.gos\"><img\r\n");
      out.write("									src=\"resources/goats_icon/hyphen.png\"><span>반려함</span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"top-menu\" href=\"gtOrganizationSelectAll.gos\"><img\r\n");
      out.write("							src=\"resources/goats_icon/project_contractor.png\"><span>조직도</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"weather3\" id=\"weather3\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../weather/weather.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 사이드바 메뉴 리스트 -->\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- 사이드바 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 각 페이지마다 사용할 content 영역 -->\r\n");
      out.write("	<div id=\"content\"></div>\r\n");
      out.write("	<!-- 각 페이지마다 사용할 content 영역 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
