/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-28 01:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.organization;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.kos.draft.vo.GtDraftVO;

public final class organizationSelectAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688555200114L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.kos.draft.vo.GtDraftVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    ");
 request.setCharacterEncoding("UTF-8");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("      .container2 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("/* //////////////////////////////////////////////// */\r\n");
      out.write("/* ///////////////////메인 css/////////////////////// */\r\n");
      out.write("/* //////////////////////////////////////////////// */\r\n");
      out.write(".basic_i01 {\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("/* 1번째 .content의 2번째 .section에 적용 */\r\n");
      out.write(".content_i01:nth-of-type(1)>.section_i01:nth-of-type(2) {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("/* 1~2의 .article 적용 */\r\n");
      out.write(".article_i01:nth-of-type(-n+2) {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("}\r\n");
      out.write("/* 2번째 .article 적용 */\r\n");
      out.write(".article_i01:nth-of-type(2) {\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("/* 테이블 기본설정 */\r\n");
      out.write(".content_i01 > table{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .content_i01 > table,td,tr{\r\n");
      out.write("	border: 1px solid #aaa;\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("/* 마지막에서 1번째 .content */\r\n");
      out.write(".content_i01:nth-last-of-type(1) {\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper_i01:first-of-type {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper_i01:last-of-type {\r\n");
      out.write("	margin: 10px auto 0 auto;\r\n");
      out.write("	padding: 0 10px 0 10px;\r\n");
      out.write("}\r\n");
      out.write(".section_i01  img {\r\n");
      out.write("	width: 15px;\r\n");
      out.write("	height: 15px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("/* 23.07.24 검색기능 input 추가 */\r\n");
      out.write(".section_i01 {display:flex;justify-content: space-between;align-items: center;    margin-bottom: 10px;}\r\n");
      out.write(".section_i01 .selectArea input{border: 1px solid #e8e8e8;border-radius: 5px;height: 30px;padding-left: 5px;outline:none;}\r\n");
      out.write(".section_i01 .selectArea button{border-radius: 5px;border: 1px solid #e8e8e8;width: 40px;height: 30px;}\r\n");
      out.write(".section_i01 .selectArea select{outline: none;height: 30px;border: 1px solid #e8e8e8;border-radius: 5px;}\r\n");
      out.write(".spaceRight{margin-right:10px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".content_01:nth-child(2) > span {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write(".content_01:nth-child(1) > span {\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".basic_i01 {\r\n");
      out.write("	border: 1px solid #aaa;\r\n");
      out.write("	width: 95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function(){\r\n");
      out.write("		performSearch();\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("  function updateTable(data) {\r\n");
      out.write("      var table = $(\"#dataBody\");\r\n");
      out.write("      table.empty(); // Clear existing content\r\n");
      out.write("\r\n");
      out.write("      $.each(data, function(index, item) {\r\n");
      out.write("         var row = $(\"<tr>\");\r\n");
      out.write("         row.append($(\"<td>\").text(item.genum));\r\n");
      out.write("         row.append($(\"<td>\").text(item.gedept));\r\n");
      out.write("         row.append($(\"<td>\").text(item.title));\r\n");
      out.write("         row.append($(\"<td>\").text(item.gename));\r\n");
      out.write("         row.append($(\"<td>\").text(item.geid));\r\n");
      out.write("         row.append($(\"<td>\").text(item.geemail));\r\n");
      out.write("         row.append($(\"<td>\").text(item.gehp));\r\n");
      out.write("\r\n");
      out.write("         table.append(row);\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("  function performSearch() {\r\n");
      out.write("	  console.log(\"search starts\")\r\n");
      out.write("      let searchGename = $(\"#searchGename\").val();\r\n");
      out.write("	  let searchGedept = $(\"#searchGedept\").val();\r\n");
      out.write("	 \r\n");
      out.write("	  \r\n");
      out.write("	  let dataToSend = {\r\n");
      out.write("		         gename: searchGename,\r\n");
      out.write("		         gedept: searchGedept\r\n");
      out.write("		      };\r\n");
      out.write("	  \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type: \"GET\",\r\n");
      out.write("         url : \"gtOrganizationSelectAll2.gos\",\r\n");
      out.write("         data: dataToSend,\r\n");
      out.write("         success: function(data) {\r\n");
      out.write("        	console.log(data)\r\n");
      out.write("            updateTable(data.aList); // 기존 controller > rest방식으로 변경  json직렬화까지 해놓음\r\n");
      out.write("         },\r\n");
      out.write("         error: function() {\r\n");
      out.write("            alert(\"Error occurred during search.\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container2\">\r\n");
      out.write("		<div>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/mainSide-bar.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("     	 <div style=\"margin: 0; padding: 0; width:100%;\">\r\n");
      out.write("       		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/Top-bar.jsp", out, false);
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("<!--         //////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<!--         //////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<!--         //////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("			<div class=\"basic_i01\">\r\n");
      out.write("				<div class=\"wrapper_i01\">\r\n");
      out.write("					<div class=\"content_01\">\r\n");
      out.write("						<span>조직도</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content_01 spaceRight\">\r\n");
      out.write("						<span>Home</span> / 조직도 \r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"wrapper_i01\">\r\n");
      out.write("					<div class=\"content_i01\">\r\n");
      out.write("						<div class=\"section_i01\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<img src=\"\\resources\\goats_icon\\my.png\" alt=\"img\"> <span>조직도 인원 현황</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"selectArea\">\r\n");
      out.write("							<select id=\"searchGedept\" class=\"\"> <!-- 구분 -->\r\n");
      out.write("					      		<option value=\"\">-전체-</option>\r\n");
      out.write("					      		<option value=\"인사팀\">인사팀</option>\r\n");
      out.write("					      		<option value=\"개발1팀\">개발1팀</option>\r\n");
      out.write("					      		<option value=\"영업팀\">영업팀</option>\r\n");
      out.write("					      		<option value=\"개발2팀\">개발2팀</option>\r\n");
      out.write("					      		<option value=\"개발3팀\">개발3팀</option>\r\n");
      out.write("					      		<option value=\"대표이사\">대표이사</option>\r\n");
      out.write("					      	</select>\r\n");
      out.write("							<input type=\"text\" id=\"searchGename\" placeholder=\"이름입력\">\r\n");
      out.write("							<button onclick=\"performSearch()\">검색</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content_i01\" style='overflow-x: hidden; height: 728px;'>\r\n");
      out.write("						<table >\r\n");
      out.write("							<!-- js로 오름, 내림 처리 -->\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>사번</td>\r\n");
      out.write("								<td>부서</td>\r\n");
      out.write("								<td>직급</td>\r\n");
      out.write("								<td>이름</td>\r\n");
      out.write("								<td>아이디</td>\r\n");
      out.write("								<td>메일</td>\r\n");
      out.write("								<td>연락처</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tbody id=\"dataBody\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>                  \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/organization/organizationSelectAll.jsp(203,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /WEB-INF/views/organization/organizationSelectAll.jsp(203,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/organization/organizationSelectAll.jsp(203,8) '${aList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${aList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								   <tr>\r\n");
            out.write("								      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.genum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.gedept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.gename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.geid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.geemail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.gehp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								   </tr>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
