/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 08:00:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.resignation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.common.chabun.service.GtChabunServiceImpl;
import com.gt.s.common.DateFormatUtil;
import com.gt.s.common.ChabunUtil;
import com.gt.s.common.chabun.dao.GtChabunDAOImpl;
import com.gt.s.common.chabun.dao.GtChabunDAO;
import com.gt.s.common.chabun.service.GtChabunService;
import com.gt.s.kos.resignation.vo.GtResignationVO;

public final class resignationInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:split", org.apache.taglibs.standard.functions.Functions.class, "split", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688555200114L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.common.DateFormatUtil");
    _jspx_imports_classes.add("com.gt.s.kos.resignation.vo.GtResignationVO");
    _jspx_imports_classes.add("com.gt.s.common.ChabunUtil");
    _jspx_imports_classes.add("com.gt.s.common.chabun.service.GtChabunService");
    _jspx_imports_classes.add("com.gt.s.common.chabun.dao.GtChabunDAOImpl");
    _jspx_imports_classes.add("com.gt.s.common.chabun.service.GtChabunServiceImpl");
    _jspx_imports_classes.add("com.gt.s.common.chabun.dao.GtChabunDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>사직서</title>\r\n");
      out.write("<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\"rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">   \r\n");
      out.write("   // ready() 시작\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("      //실행시 채번 가져오기\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : \"gtResignationChanbun.gos\",\r\n");
      out.write("         success: function(res) {               \r\n");
      out.write("            console.log(\">>> res : \" + res);\r\n");
      out.write("            \r\n");
      out.write("            $('#grnum1').text(res);\r\n");
      out.write("            $('#grnum').val(res);\r\n");
      out.write("         },\r\n");
      out.write("         error: function(e) {\r\n");
      out.write("            console.log(e.reponseText);\r\n");
      out.write("         }\r\n");
      out.write("      }); // 채번 화면에 표시\r\n");
      out.write("      \r\n");
      out.write("      // btnSend 클릭시\r\n");
      out.write("      $(document).on('click', '#btnSend', function() {            \r\n");
      out.write("         // 결재선\r\n");
      out.write("         var hu1 = $(\"#hu1\").text()\r\n");
      out.write("         var hu2 = $(\"#hu2\").text()\r\n");
      out.write("         var hu3 = $(\"#hu3\").text()\r\n");
      out.write("         var hu4 = $(\"#hu4\").text()\r\n");
      out.write("         var hu5 = $(\"#hu5\").text()\r\n");
      out.write("         \r\n");
      out.write("         $(\"#hu1_1\").val(hu1);\r\n");
      out.write("         $(\"#hu2_1\").val(hu2);\r\n");
      out.write("         $(\"#hu3_1\").val(hu3);\r\n");
      out.write("         $(\"#hu4_1\").val(hu4);\r\n");
      out.write("         $(\"#hu5_1\").val(hu5);\r\n");
      out.write("         \r\n");
      out.write("         var dep1 = $(\"#dep1\").text()\r\n");
      out.write("         var dep2 = $(\"#dep2\").text()\r\n");
      out.write("         var dep3 = $(\"#dep3\").text()\r\n");
      out.write("         var dep4 = $(\"#dep4\").text()\r\n");
      out.write("         var dep5 = $(\"#dep5\").text()\r\n");
      out.write("         \r\n");
      out.write("         $(\"#dept1_1\").val(dep1);\r\n");
      out.write("         $(\"#dept2_1\").val(dep2);\r\n");
      out.write("         $(\"#dept3_1\").val(dep3);\r\n");
      out.write("         $(\"#dept4_1\").val(dep4);\r\n");
      out.write("         $(\"#dept5_1\").val(dep5);\r\n");
      out.write("         \r\n");
      out.write("         // input 히든에 벨류 값 보냄\r\n");
      out.write("         var cc = $(\"#reference01\").text();            \r\n");
      out.write("         \r\n");
      out.write("         $(\"#reference\").val(cc);\r\n");
      out.write("         alert(\">>> reference :\" + $(\"#reference\").val());\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         // editor 데이터 세팅\r\n");
      out.write("         var ql = $('.ql-editor').html();   \r\n");
      out.write("         var qui = $(\"#grmemo\").val(ql);\r\n");
      out.write("         \r\n");
      out.write("         // 데이터 세팅\r\n");
      out.write("         let dataParam = $(\"#form01\").serialize();  \r\n");
      out.write("         // 텍스트 먼저 전송\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url: 'resignationInsert.gos',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            data: dataParam,\r\n");
      out.write("            success: function(res) {\r\n");
      out.write("               console.log(\">>> Success !!!\" + res);\r\n");
      out.write("               \r\n");
      out.write("               if(res == 'YES') {                     \r\n");
      out.write("                  $('#form02').attr({\r\n");
      out.write("                     'action':'gtResignationInsertFile.gos',\r\n");
      out.write("                     'method':'POST',\r\n");
      out.write("                     'encType':'multipart/form-data'\r\n");
      out.write("                  }).submit();                     \r\n");
      out.write("               }else {\r\n");
      out.write("                  alert(\">>> grfile Insert Fail\");\r\n");
      out.write("               }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(e) {\r\n");
      out.write("               alert(e.responseText);\r\n");
      out.write("            }\r\n");
      out.write("         });            \r\n");
      out.write("      }); // end of btnSend.click()\r\n");
      out.write("      \r\n");
      out.write("      // 결재선지정 버튼\r\n");
      out.write("      $(document).on(\"click\", \"#btnapro\", function() {\r\n");
      out.write("         \r\n");
      out.write("         $(\"#approval\").css({\r\n");
      out.write("            \"visibility\" : \"visible\"\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         $(\"#hide_div\").hide();\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      // 취소 버튼\r\n");
      out.write("      $(\"#btnCancle\").click(function(){\r\n");
      out.write("         window.close();\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      // 작성일자 자동입력\r\n");
      out.write("      document.getElementById('currentDate').innerText = new Date().toISOString().slice(0,10);\r\n");
      out.write("      \r\n");
      out.write("   }); // end of ready()\r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("   .button-container {\r\n");
      out.write("      text-align: right;\r\n");
      out.write("      width:1000px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .initial-size {\r\n");
      out.write("      min-height: 200px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   th {\r\n");
      out.write("      background-color: #f2f2f2;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   table {\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("      width: 1000px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   th, td {\r\n");
      out.write("      border: 1px solid black;\r\n");
      out.write("      padding: 8px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #approval {\r\n");
      out.write("      visibility: hidden;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("   }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"approval\" >\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../approvalline/select.jsp", out, false);
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   <div id=\"hide_div\" class=\"hide_div\">\r\n");
      out.write("      <form id=\"form01\" name=\"form01\">\r\n");
      out.write("         <div class=\"button-container\">\r\n");
      out.write("            <button type=\"button\" id=\"btnapro\">결재선지정</button>\r\n");
      out.write("            <button type=\"button\" id=\"btnSend\">상신</button>\r\n");
      out.write("            <button type=\"button\" id=\"btnCancle\">취소</button>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div align=\"center\">\r\n");
      out.write("            <span class=\"sp\"><strong>사 직 서</strong></span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <br>\r\n");
      out.write("         <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">문서번호</th>\r\n");
      out.write("               <td width=\"230px\" id=\"grnum1\"></td>\r\n");
      out.write("               <th width=\"120px\">보안구분</th>\r\n");
      out.write("               <td width=\"230px\">비공개</td>\r\n");
      out.write("               <th width=\"120px\">보존연한</th>\r\n");
      out.write("               <td width=\"230px\">5년</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"100px\">작성자</th>\r\n");
      out.write("               <td width=\"230px\" id=\"writer01\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(writer01, '/', ' ')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</td>\r\n");
      out.write("               <th width=\"100px\">작성일자</th>\r\n");
      out.write("               <td colspan=\"3\" id=\"currentDate\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br>\r\n");
      out.write("         <table class=\"table1\" id=\"table1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"20px\">순서</th>\r\n");
      out.write("               <th width=\"80px\">구분</th>\r\n");
      out.write("               <th width=\"17px\">결재자</th>\r\n");
      out.write("               <th width=\"17px\">부서</th>\r\n");
      out.write("               <th width=\"8px\">상태</th>\r\n");
      out.write("               <th width=\"10px\">결재일</th>\r\n");
      out.write("               <th width=\"35px\">결재의견</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr align=\"center\">\r\n");
      out.write("               <td>1</td>\r\n");
      out.write("               <td id=\"snag1\"></td>\r\n");
      out.write("               <td id=\"hu1\"></td>\r\n");
      out.write("               <td id=\"dep1\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr align=\"center\">\r\n");
      out.write("               <td>2</td>\r\n");
      out.write("               <td id=\"snag2\"></td>\r\n");
      out.write("               <td id=\"hu2\"></td>\r\n");
      out.write("               <td id=\"dep2\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr align=\"center\">\r\n");
      out.write("               <td>3</td>\r\n");
      out.write("               <td id=\"snag3\"></td>\r\n");
      out.write("               <td id=\"hu3\"></td>\r\n");
      out.write("               <td id=\"dep3\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr align=\"center\">\r\n");
      out.write("               <td>4</td>\r\n");
      out.write("               <td id=\"snag4\"></td>\r\n");
      out.write("               <td id=\"hu4\"></td>\r\n");
      out.write("               <td id=\"dep4\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr align=\"center\">\r\n");
      out.write("               <td>5</td>\r\n");
      out.write("               <td id=\"snag5\"></td>\r\n");
      out.write("               <td id=\"hu5\"></td>\r\n");
      out.write("               <td id=\"dep5\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br>\r\n");
      out.write("         <table id=\"cham1\" class=\"cham1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">참 조</th>\r\n");
      out.write("               <td id=\"reference01\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br>\r\n");
      out.write("         <table class=\"tab t04\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">제 목</th>\r\n");
      out.write("               <td><input type=\"text\" name=\"grsubject\" id=\"grsubject\"\r\n");
      out.write("                  style=\"width: 820px\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br>\r\n");
      out.write("         <table class=\"tab t05\">         \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">직 급</th>\r\n");
      out.write("               <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(writer01,'/')[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">성 명</th>\r\n");
      out.write("               <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(writer01,'/')[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">입 사 일</th>\r\n");
      out.write("               <td><input type=\"date\" name=\"grstartdate\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">최종근무일</th>\r\n");
      out.write("               <td><input type=\"date\" name=\"grenddate\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("         <table class=\"tab t06\">\r\n");
      out.write("            <th>비고</th>\r\n");
      out.write("            <br>\r\n");
      out.write("         </table>\r\n");
      out.write("   \r\n");
      out.write("         <div id=\"editor\" class=\"initial-size\"></div>\r\n");
      out.write("         <script>\r\n");
      out.write("            var quill = new Quill('#editor', {\r\n");
      out.write("            // Quill 설정 옵션\r\n");
      out.write("            });\r\n");
      out.write("      \r\n");
      out.write("            // 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("            var editorContainer = document.querySelector('#editor');\r\n");
      out.write("               editorContainer.addEventListener('click', function() {\r\n");
      out.write("                  quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("            });\r\n");
      out.write("      \r\n");
      out.write("            var toolbarOptions = [  [ 'bold', 'italic', 'underline', 'strike' ],\r\n");
      out.write("                              [ 'link', 'image' ], \r\n");
      out.write("                              [ {'list' : 'ordered'}, {'list' : 'bullet'} ],\r\n");
      out.write("                              [ {'header' : [ 1, 2 ]} ] \r\n");
      out.write("                            ];\r\n");
      out.write("      \r\n");
      out.write("            var quill = new Quill('#editor', {\r\n");
      out.write("               modules : {toolbar : toolbarOptions},theme : 'snow'\r\n");
      out.write("               });\r\n");
      out.write("      \r\n");
      out.write("            function myFunction() {\r\n");
      out.write("               alert(\"gd\");\r\n");
      out.write("            }\r\n");
      out.write("         </script>\r\n");
      out.write("   \r\n");
      out.write("         <br>\r\n");
      out.write("      \r\n");
      out.write("         <!-- 가공값 세팅 -->      \r\n");
      out.write("         <input type=\"hidden\" name=\"grnum\"    id=\"grnum\">\r\n");
      out.write("         <input type=\"hidden\" name=\"grmemo\"   id=\"grmemo\" >\r\n");
      out.write("         <!-- session에서 받아올 값 -->\r\n");
      out.write("         <input type=\"hidden\" name=\"genum\"      id=\"genum\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${genum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("         <input type=\"hidden\" name=\"writer\"     id=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(writer01, '/', ' ')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">\r\n");
      out.write("         <!-- 결재선 지정 받을 곳 -->\r\n");
      out.write("         <input type=\"hidden\" name=\"proval\"   id=\"proval\"    >\r\n");
      out.write("         <input type=\"hidden\" name=\"reference\"id=\"reference\" >\r\n");
      out.write("         \r\n");
      out.write("         <input type=\"hidden\" name=\"approver\"id=\"hu1_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"approver\"id=\"hu2_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"approver\"id=\"hu3_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"approver\"id=\"hu4_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"approver\"id=\"hu5_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"dept\"    id=\"dept1_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"dept\"    id=\"dept2_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"dept\"    id=\"dept3_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"dept\"    id=\"dept4_1\"     >\r\n");
      out.write("         <input type=\"hidden\" name=\"dept\"    id=\"dept5_1\"     >\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 파일업로드  -->\r\n");
      out.write("      <form id=\"form02\" name=\"form02\">\r\n");
      out.write("         <table class=\"tab t07\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"120px\">첨부파일</th>\r\n");
      out.write("               <td><input type=\"file\" name=\"grfile\" id=\"grfile\" size=\"100%\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/resignation/resignationInsertForm.jsp(166,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("writer01");
      // /WEB-INF/views/resignation/resignationInsertForm.jsp(166,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/resignation/resignationInsertForm.jsp(166,3) '${writer}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${writer}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
