/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 08:10:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.resignation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.common.chabun.service.GtChabunServiceImpl;
import com.gt.s.common.DateFormatUtil;
import com.gt.s.common.ChabunUtil;
import com.gt.s.common.chabun.dao.GtChabunDAOImpl;
import com.gt.s.common.chabun.dao.GtChabunDAO;
import com.gt.s.common.chabun.service.GtChabunService;
import com.gt.s.kos.resignation.vo.GtResignationVO;
import com.gt.s.common.CodeUtil;

public final class resignationSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.common.DateFormatUtil");
    _jspx_imports_classes.add("com.gt.s.kos.resignation.vo.GtResignationVO");
    _jspx_imports_classes.add("com.gt.s.common.ChabunUtil");
    _jspx_imports_classes.add("com.gt.s.common.chabun.service.GtChabunService");
    _jspx_imports_classes.add("com.gt.s.common.CodeUtil");
    _jspx_imports_classes.add("com.gt.s.common.chabun.dao.GtChabunDAOImpl");
    _jspx_imports_classes.add("com.gt.s.common.chabun.service.GtChabunServiceImpl");
    _jspx_imports_classes.add("com.gt.s.common.chabun.dao.GtChabunDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	GtResignationVO rvo = (GtResignationVO)request.getAttribute("rvo");
	String app = rvo.getApprover();
	String count = rvo.getCount();
	String s = CodeUtil.edsmjeoncheck(app, Integer.parseInt(count));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("	<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("	<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("			var app = '");
      out.print(rvo.getApprover());
      out.write("';\r\n");
      out.write("			var dept = '");
      out.print(rvo.getDept());
      out.write("';\r\n");
      out.write("			var pro = '");
      out.print(rvo.getProval());
      out.write("';\r\n");
      out.write("			var appcount = '");
      out.print(rvo.getCount());
      out.write("';\r\n");
      out.write("			var writer = '");
      out.print(rvo.getWriter());
      out.write("';\r\n");
      out.write("			var s = '");
      out.print(s);
      out.write("';\r\n");
      out.write("			var app_ = app.split(\"/\");\r\n");
      out.write("			var dept_ = dept.split(\"/\");\r\n");
      out.write("\r\n");
      out.write("			var info = '");
      out.print(rvo.getGrmemo());
      out.write("';\r\n");
      out.write("			var info_ = info.split(\",\");\r\n");
      out.write("			$('#memo').html(info);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			var writer01 = writer.split(\" \");\r\n");
      out.write("			$('#name').text(writer01[1]);\r\n");
      out.write("			$('#dept').text(writer01[2]);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			if(pro != 'null') {\r\n");
      out.write("				var pro_ = pro.split(\"/\");\r\n");
      out.write("			}else {\r\n");
      out.write("				var pro_ = \"\";\r\n");
      out.write("			}\r\n");
      out.write("			console.log(\"s > : \" + s);\r\n");
      out.write("			if(appcount < 0) {\r\n");
      out.write("				var nappcount = Number(appcount) + 10;\r\n");
      out.write("				for(var i=0; i<app_.length; i++) {\r\n");
      out.write("					if(app_[i] != \"-\"){\r\n");
      out.write("						if(app_[i] != \"-\"){\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("							if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("						if(nappcount == i) {\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("							if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"반려\");\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}else {\r\n");
      out.write("				if(s != '') {\r\n");
      out.write("					for(var i=0; i<app_.length; i++) {\r\n");
      out.write("						if(app_[i] != \"-\"){\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(appcount-9)+\")\").find(\"td:eq(5)\").text(pro_[0]);\r\n");
      out.write("							if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"전결\");\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				}else {\r\n");
      out.write("					for(var i=0; i<app_.length; i++) {\r\n");
      out.write("						if(app_[i] != \"-\"){\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("							$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("							if($(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			var num = '");
      out.print( rvo.getGrnum());
      out.write("';\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"refileDownloadlist.gos\",\r\n");
      out.write("				type:\"GET\",\r\n");
      out.write("				data:{\"grnum\":num},\r\n");
      out.write("				success:whens\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			function whens(d) {\r\n");
      out.write("				var filename = d.split(\",\");\r\n");
      out.write("				for(var i=0; i<filename.length-1; i++) {\r\n");
      out.write("					$(\"#table3\").find(\"tr:eq(0)\").find(\"td:eq(0)\").append(\"<a href='fileDownloadref?file=\"+filename[i]+\"&num=\"+num+\"' target='_blank'>\"+filename[i]+\"</a><br>\");\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	.button-container {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.initial-size {\r\n");
      out.write("		min-height: 200px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	th {\r\n");
      out.write("		background-color: #f2f2f2;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table {\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		width: 1000px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	th, td {\r\n");
      out.write("		border: 1px solid black;\r\n");
      out.write("		padding: 8px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#approval {\r\n");
      out.write("		visibility: hidden;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		background-color: #fff;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<div id=\"approval\" style=\"width:1033px;\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../approvalline/select.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	 <form id=\"form01\" name=\"form01\">\r\n");
      out.write("		<div class=\"button-container\">\r\n");
      out.write("			<button type=\"button\" id=\"line12\">결재선지정</button>\r\n");
      out.write("			<button type=\"button\" id=\"btnSend\">상신</button>\r\n");
      out.write("			<button type=\"button\" id=\"btnCancle\" onclick=\"javascript:btnCancle()\">취소</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<span class=\"sp\"><strong>사 직 서</strong></span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"table1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">문서번호</th>\r\n");
      out.write("				<td width=\"230px\" id=\"grnum\">");
      out.print( rvo.getGrnum() );
      out.write("</td>\r\n");
      out.write("				<th width=\"120px\">보안구분</th>\r\n");
      out.write("				<td width=\"230px\">비공개</td>\r\n");
      out.write("				<th width=\"120px\">보존연한</th>\r\n");
      out.write("				<td width=\"230px\">5년</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"100px\">작성자</th>\r\n");
      out.write("				<td width=\"230px\" id=\"writer\">");
      out.print( rvo.getWriter() );
      out.write("</td>\r\n");
      out.write("				<th width=\"100px\">작성일자</th>\r\n");
      out.write("				<td colspan=\"3\" id=\"currentDate\">");
      out.print( rvo.getInsertdate() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table id=\"table1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"50px\">순서</th>\r\n");
      out.write("				<th width=\"80px\">구분</th>\r\n");
      out.write("				<th width=\"170px\">결재자</th>\r\n");
      out.write("				<th width=\"170px\">부서</th>\r\n");
      out.write("				<th width=\"80px\">상태</th>\r\n");
      out.write("				<th width=\"100px\">결재일</th>\r\n");
      out.write("				<th width=\"350px\">결재의견</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">1</td>\r\n");
      out.write("				<td id=\"snag1\"></td>\r\n");
      out.write("				<td id=\"hu1\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept1\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">2</td>\r\n");
      out.write("				<td id=\"snag2\"></td>\r\n");
      out.write("				<td id=\"hu2\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept2\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">3</td>\r\n");
      out.write("				<td id=\"snag3\"></td>\r\n");
      out.write("				<td id=\"hu3\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept3\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">4</td>\r\n");
      out.write("				<td id=\"snag4\"></td>\r\n");
      out.write("				<td id=\"hu4\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept4\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">5</td>\r\n");
      out.write("				<td id=\"snag5\"></td>\r\n");
      out.write("				<td id=\"hu5\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept5\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table id=\"cham1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("           	");
 if(rvo.getReference() == null) {
           		rvo.setReference(" ");
            } 
      out.write("\r\n");
      out.write("				<th width=\"133px\">참 조</th>\r\n");
      out.write("				<td id=\"cham\">");
      out.print( rvo.getReference() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"tab t04\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">제 목</th>\r\n");
      out.write("				<td>");
      out.print( rvo.getGrsubject() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"tab t05\">\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">직 급</th>\r\n");
      out.write("				<td id=\"dept\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">성 명</th>\r\n");
      out.write("				<td id=\"name\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">입 사 일</th>\r\n");
      out.write("				<td>");
      out.print( rvo.getGrstartdate() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\" >퇴 사 일</th>\r\n");
      out.write("				<td>");
      out.print( rvo.getGrenddate() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"tab t06\">\r\n");
      out.write("			<th>비고</th>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td id=\"memo\"  style=\"text-align:left\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	<form id=\"form02\" name=\"form02\">\r\n");
      out.write("		<table  class=\"table3\" id=\"table3\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">첨부파일</th>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
