/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-27 01:17:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.employee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.gt.s.kos.schedule.vo.GtScheduleVO;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import com.gt.s.kos.employee.vo.GtEmployeeVO;

public final class gtEmployeeSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gt.s.kos.employee.vo.GtEmployeeVO");
    _jspx_imports_classes.add("com.gt.s.kos.schedule.vo.GtScheduleVO");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Logger log = LogManager.getLogger(this.getClass());
	List<GtEmployeeVO> list = (List<GtEmployeeVO>)request.getAttribute("list");
	GtEmployeeVO evo = list.get(0);
	log.info("mainpage.jsp");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"kr\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	var gender = '");
      out.print(evo.getGegender());
      out.write("';\r\n");
      out.write("    	var apryn = '");
      out.print(evo.getApryn());
      out.write("';\r\n");
      out.write("    	var notiyn = '");
      out.print(evo.getNotiyn());
      out.write("';\r\n");
      out.write("    	\r\n");
      out.write("    	if(gender == \"1\"){\r\n");
      out.write("    		$(\"#men\").prop({\"checked\":true});\r\n");
      out.write("    	}else{\r\n");
      out.write("    		$(\"#women\").prop({\"checked\":true});\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	if(apryn == \"Y\") {\r\n");
      out.write("    		$(\"#apryn\").prop({\"checked\":true});\r\n");
      out.write("    	}\r\n");
      out.write("    	if(notiyn == \"Y\") {\r\n");
      out.write("    		$(\"#notiyn\").prop({\"checked\":true});\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	$(\".gender\").click(function() {\r\n");
      out.write("    		$(\".gender\").prop({\"checked\":false});\r\n");
      out.write("    		$(this).prop({\"checked\":true});\r\n");
      out.write("    	});\r\n");
      out.write("    	\r\n");
      out.write("    	$(document).on(\"click\", \"#update_btn\", function() {\r\n");
      out.write("    		$(\"#emp_update_form\").attr({\r\n");
      out.write("    			\"action\":\"gtEmployeeUpdate.gos\",\r\n");
      out.write("    			\"method\":\"GET\"\r\n");
      out.write("    		}).submit();\r\n");
      out.write("    	});\r\n");
      out.write("    	\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			//다음 주소\r\n");
      out.write("			$(\"#gezone\").prop(\"readonly\", true);\r\n");
      out.write("			$(\"#geload\").prop(\"readonly\", true);\r\n");
      out.write("			$(\"#gejibun\").prop(\"readonly\", true);\r\n");
      out.write("			$(\"#zonecode\").click(function(){\r\n");
      out.write("				console.log(\"zonecode >>> : \");\r\n");
      out.write("				new daum.Postcode({\r\n");
      out.write("					oncomplete: function(data) {\r\n");
      out.write("						$(\"#gezone\").val(data.zonecode);\r\n");
      out.write("						$(\"#geroad\").val(data.roadAddress);\r\n");
      out.write("						$(\"#gejibun\").val(data.jibunAddress);\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}).open();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#rightcon {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	margin: 2px;\r\n");
      out.write("	height: 28px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("	text-align:center;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("	boerder: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container2 {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"width: 100%\">\r\n");
      out.write("	<div class=\"container2\" style=\"margin: 0; width: 100%;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/mainSide-bar.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"margin: 0; padding: 0; width: 100%;\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/Top-bar.jsp", out, false);
      out.write("\r\n");
      out.write("			<div class=\"container\" id=\"rightcon\">\r\n");
      out.write("				<div style=\"width: 500px; margin-right: auto; margin-left: auto;\">\r\n");
      out.write("					<h1 style=\"text-align: center;\">사원 정보수정</h1>\r\n");
      out.write("					<form id=\"emp_update_form\">\r\n");
      out.write("					<table style=\"text-align: center; width: 500px; height: 600px;\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th style=\"height: 10px;\"></th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr style=\"margin-top: 10px\">\r\n");
      out.write("							<th style=\"margin: 30px;\">사원번호</th>\r\n");
      out.write("							<th>사원명</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"text\" readonly=\"readonly\" value=\"");
      out.print(evo.getGenum() );
      out.write("\" name=\"genum\"></td>\r\n");
      out.write("							<td><input type=\"text\" readonly=\"readonly\" value=\"");
      out.print(evo.getGename() );
      out.write("\" name=\"gename\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>아이디</th>\r\n");
      out.write("							<th>비밀번호</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getGeid() );
      out.write("\" name=\"geid\"></td>\r\n");
      out.write("							<td><input type=\"password\" style=\"width: 90%; height: 28px;\" value=\"");
      out.print(evo.getGepw() );
      out.write("\" name=\"gepw\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>성별</th>\r\n");
      out.write("							<th>생년월일</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>남자<input type=\"checkbox\" id=\"men\" class=\"gender\" name=\"gegender\" value=\"1\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("							       여자<input type=\"checkbox\" id=\"women\" class=\"gender\"name=\"gegender\" value=\"2\"></td>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getGebirth() );
      out.write("\" name=\"gebirth\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>핸드폰 번호</th>\r\n");
      out.write("							<th>이메일</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getGehp());
      out.write("\" name=\"gehp\"></td>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getGeemail());
      out.write("\" name=\"geemail\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th style=\"height: 10px;\"></th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">\r\n");
      out.write("								<table style=\"width: 95%;\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>우편번호</th>\r\n");
      out.write("										<th>도로명 주소</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td><input type=\"text\" id=\"gezone\" name=\"gezone\" value=\"");
      out.print(evo.getGezone());
      out.write("\"></td>\r\n");
      out.write("										<td><input type=\"text\" id=\"geroad\" name=\"geroad\" value=\"");
      out.print(evo.getGeroad());
      out.write("\">\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>지번주소</th>\r\n");
      out.write("										<th>상세주소</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td><input type=\"text\" id=\"gejibun\" name=\"geroaddetail\" value=\"");
      out.print(evo.getGeroaddetail());
      out.write("\"></td>\r\n");
      out.write("										<td><input type=\"text\" id=\"gejibun\" name=\"gejibun\" value=\"");
      out.print(evo.getGejibun());
      out.write("\">\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td colspan=\"2\"><input type=\"button\" name=\"zonecode\"\r\n");
      out.write("											id=\"zonecode\" value=\"우편번호 찾기\"\r\n");
      out.write("											style=\"width: 108px; height: 21px; vertical-align: middle; float: right; margin: 10px; background-color: lightblue; color: black;\">\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th style=\"height: 10px;\"></th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>부서명</th>\r\n");
      out.write("							<th>직급</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getGedept());
      out.write("\" name=\"gedept\"></td>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getTitle());
      out.write("\" name=\"title\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>공지&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;전결</th>\r\n");
      out.write("							<th>연봉</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"checkbox\" id=\"notiyn\" name=\"notiyn\"\r\n");
      out.write("								style=\"margin-right: 30px;\" value=\"Y\"><input type=\"checkbox\"\r\n");
      out.write("								id=\"apryn\" name=\"apryn\" style=\"margin-left: 30px;\" value=\"Y\"></td>\r\n");
      out.write("							<td><input type=\"text\" value=\"");
      out.print(evo.getSalary());
      out.write("\" name=\"salary\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th style=\"height: 10px;\"></th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div style=\"float: right;\">\r\n");
      out.write("						<input type=\"button\" value=\"수정\" id=\"update_btn\"\r\n");
      out.write("							style=\"width: 108px; height: 21px; vertical-align: middle; background-color: lightblue; color: black; margin-top: 10px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
