/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 07:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.approvalline;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.gt.s.kos.dept.vo.GtDeptVO;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
    _jspx_imports_classes.add("com.gt.s.kos.dept.vo.GtDeptVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      \r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("         \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"goatsDeptSelectAll.gos\",\r\n");
      out.write("         type:\"POST\",\r\n");
      out.write("         success:whens\r\n");
      out.write("      });\r\n");
      out.write("      function whens(data) {\r\n");
      out.write("         var data = data.split(\",\");\r\n");
      out.write("         for(let i=0; i<data.length-1; i++) {\r\n");
      out.write("           if(data[i] === \"대표이사\"){\r\n");
      out.write("            $(\"#jojic\").append(\"<li><div class='select' style='border:1px solid darkgray;'><span class='aas'><img src='resources/goats_icon/person.png' style='width:18px; height:18px; margin-left:5px; margin-right:5px; margin-top:5px;'></spna><span style='vertical-align:3px; margin-left:1px;'>\" + data[i] + \"</span></div></li>\");           \r\n");
      out.write("           }else if(data[i] === \"영업팀\"){\r\n");
      out.write("            $(\"#jojic\").append(\"<li><div class='select' style='border:1px solid darkgray;'><span class='aas'><img src='resources/goats_icon/member.png' style='width:18px; height:18px; margin-left:5px; margin-right:5px; margin-top:5px;'></spna><span style='vertical-align:3px; margin-left:5px;'>\" + data[i] + \"</span></div></li>\");\r\n");
      out.write("           }else if(data[i] === \"인사팀\"){\r\n");
      out.write("            $(\"#jojic\").append(\"<li><div class='select' style='border:1px solid darkgray;'><span class='aas'><img src='resources/goats_icon/member.png' style='width:18px; height:18px; margin-left:5px; margin-right:5px; margin-top:5px;'></spna><span style='vertical-align:3px; margin-left:5px;'>\" + data[i] + \"</span></div></li>\");\r\n");
      out.write("           }else{\r\n");
      out.write("           $(\"#jojic\").append(\"<li><div class='select' style='border:1px solid darkgray;'><span class='aas'><img src='resources/goats_icon/member.png' style='width:18px; height:18px; margin-left:5px; margin-right:5px; margin-top:5px;'></spna><span style='vertical-align:3px; margin-left:2px;'>\" + data[i] + \"</span></div></li>\");\r\n");
      out.write("        }\r\n");
      out.write("       }         \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      $(document).on('click', '.aas', function() {\r\n");
      out.write("         var s = $(this).text();\r\n");
      out.write("         $(\"#t2\").empty();\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"goatsEmployeeSelect.gos\",\r\n");
      out.write("            data : {dept : s},\r\n");
      out.write("            method : 'GET',\r\n");
      out.write("            success : function(data){\r\n");
      out.write("                     \r\n");
      out.write("               var row = data.split(\"/\");\r\n");
      out.write("               $(\"#t2\").append(\"<tr class='white'>\" \r\n");
      out.write("                                  + \"<td class=font12_1 style='width:34%; border:1px solid white; color:white; background-color:#A4A4A4;'>이름</td>\" \r\n");
      out.write("                                  + \"<td class=font12_1 style='border:1px solid white; color:white; background-color:#A4A4A4;'>직급</td>\" \r\n");
      out.write("                                  + \"<td class=font12_1 style='width:40%; border:1px solid white; color:white; background-color:#A4A4A4;'>부서</td>\" \r\n");
      out.write("                                 + \"</tr>\");\r\n");
      out.write("                  for (var i = 0 ; i < row.length -1 ; i++ ) {\r\n");
      out.write("                     var list = row[i].split(\",\");\r\n");
      out.write("                                           \r\n");
      out.write("                        if(list[1] === \"대표이사\" ){\r\n");
      out.write("                           $(\"#t2\").append(\"<tr class='qq'><td class=font12>\"+list[0]+\"</td>\"\r\n");
      out.write("                                    + \"<td class=font10>\"+list[1]+\"</td>\"\r\n");
      out.write("                                    + \"<td class=font10 style='width:500px;'>\"+list[2]+\"</td></tr>\");\r\n");
      out.write("                        }else{\r\n");
      out.write("                           $(\"#t2\").append(\"<tr class='qq white font12_1'><td class=font12_1>\"+list[0]+\"</td>\"\r\n");
      out.write("                                    + \"<td class=font12_1>\"+list[1]+\"</td>\"\r\n");
      out.write("                                    + \"<td class=font12_1>\"+list[2]+\"</td></tr>\");\r\n");
      out.write("                        }\r\n");
      out.write("                        \r\n");
      out.write("                     } // end of for\r\n");
      out.write("                     \r\n");
      out.write("                  } // end of success\r\n");
      out.write("                         \r\n");
      out.write("               }); // end of ajax\r\n");
      out.write("               \r\n");
      out.write("            }); // end of click           \r\n");
      out.write("            \r\n");
      out.write("      $(document).on(\"click\", \"#applober\", function(){\r\n");
      out.write("               \r\n");
      out.write("               if($(\".sele\").length != 0){\r\n");
      out.write("                  var name = $(\".sele\").children(\"td:eq(0)\").text();\r\n");
      out.write("                  var si = $(\".sele\").children(\"td:eq(1)\").text();\r\n");
      out.write("                  var deft = $(\".sele\").children(\"td:eq(2)\").text();\r\n");
      out.write("\r\n");
      out.write("               for(var i=0; i<$(\".ss\").length; i++) {\r\n");
      out.write("                  var n = $(\"#applovalt\").find(\"tr:eq(\"+(i+1)+\")\").children(\"td:eq(1)\").text();\r\n");
      out.write("                  if(n == name){\r\n");
      out.write("                  \r\n");
      out.write("                  return true;\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("                    \r\n");
      out.write("            var line1 = $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(1)\").text();\r\n");
      out.write("            var line2 = $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(1)\").text();\r\n");
      out.write("            var line3 = $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(1)\").text();\r\n");
      out.write("            var line4 = $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(1)\").text();\r\n");
      out.write("            var line5 = $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(1)\").text();\r\n");
      out.write("                    \r\n");
      out.write("            if( line1 == \"-\"){\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(1)\").text(name);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(2)\").text(si);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(3)\").text(deft);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(4)\").text(\"결재\");\r\n");
      out.write("                       \r\n");
      out.write("                }else if(line2 == \"-\" ){\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(1)\").text(name);\r\n");
      out.write("                     $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(2)\").text(si);\r\n");
      out.write("                     $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(3)\").text(deft);\r\n");
      out.write("                     $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(4)\").text(\"결재\");\r\n");
      out.write("                       \r\n");
      out.write("                }else if(line3 == \"-\" ){\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(1)\").text(name);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(2)\").text(si);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(3)\").text(deft);\r\n");
      out.write("                    $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(4)\").text(\"결재\");\r\n");
      out.write("                   \r\n");
      out.write("                }else if(line4 == \"-\" ){\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(1)\").text(name);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(2)\").text(si);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(3)\").text(deft);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(4)\").text(\"결재\");\r\n");
      out.write("                   \r\n");
      out.write("                }else if(line5 == \"-\" ){\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(1)\").text(name);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(2)\").text(si);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(3)\").text(deft);\r\n");
      out.write("                   $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(4)\").text(\"결재\");       \r\n");
      out.write("                }\r\n");
      out.write("               }\r\n");
      out.write("      });\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \".hh\", function(){\r\n");
      out.write("               $(\".hh\").removeClass(\"selec\");\r\n");
      out.write("               $(this).toggleClass(\"selec\");\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \".ss\", function(){\r\n");
      out.write("                  $(\".ss\").removeClass(\"sel\");\r\n");
      out.write("                  $(this).toggleClass(\"sel\");\r\n");
      out.write("               });\r\n");
      out.write("               \r\n");
      out.write("            $(document).on(\"click\", \".qq\", function(){\r\n");
      out.write("               $(\".qq\").removeClass(\"sele\");\r\n");
      out.write("               $(this).toggleClass(\"sele\");\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \"#delbtn\", function(){\r\n");
      out.write("               if(($(\".sel\").length) == 0 && ($(\".selec\").length) == 0) {\r\n");
      out.write("                  \r\n");
      out.write("               }else if(($(\".sel\").length) != 0 && ($(\".selec\").length) == 0) {\r\n");
      out.write("               $(\".sel\").remove();\r\n");
      out.write("               $(\"#applovalt\").append(\"<tr class='ss td'><td style='color:white; background-color:#A4A4A4; border:1px solid white; border-left:1px solid #A4A4A4'>-</td><td style='border:1px solid #A4A4A4'>-</td><td style='border:1px solid #A4A4A4'>-</td><td style='border:1px solid #A4A4A4'>-</td><td style='border:1px solid #A4A4A4'>-</td></tr>\");\r\n");
      out.write("               \r\n");
      out.write("               $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(0)\").html(\"<span style='color:white;'><strong>1</strong></span>\");\r\n");
      out.write("               $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(0)\").html(\"<strong>2</strong>\");\r\n");
      out.write("               $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(0)\").html(\"<strong>3</strong>\");\r\n");
      out.write("               $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(0)\").html(\"<strong>4</strong>\");\r\n");
      out.write("               $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(0)\").html(\"<strong>5</strong>\");\r\n");
      out.write("               }else {\r\n");
      out.write("                  $(\".selec\").remove();\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // 참조자 집어넣는 펑션\r\n");
      out.write("            $(document).on('click', \"#reference_btn\", function(){\r\n");
      out.write("            var name = $(\".sele\").children(\"td:eq(0)\").text();\r\n");
      out.write("            var si = $(\".sele\").children(\"td:eq(1)\").text();\r\n");
      out.write("            var dept = $(\".sele\").children(\"td:eq(2)\").text();\r\n");
      out.write("            \r\n");
      out.write("            if(name.length > 0){\r\n");
      out.write("               var isDuplicate = false;\r\n");
      out.write("               \r\n");
      out.write("               $(\".hh\").each(function() {\r\n");
      out.write("                  var n = $(this).children(\"td:eq(0)\").text();\r\n");
      out.write("                  if (n === name) {\r\n");
      out.write("                     isDuplicate = true;\r\n");
      out.write("                     return false; // 중복된 이름을 찾았으므로 반복문을 종료합니다.\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("            \r\n");
      out.write("               if (isDuplicate) {\r\n");
      out.write("                  alert(\"중복된 이름이 이미 존재합니다.\");\r\n");
      out.write("                  return;\r\n");
      out.write("               }\r\n");
      out.write("            \r\n");
      out.write("               $(\"#t3\").append(\"<tr class='hh'><td class=chamjo style='width:31%; text-align:center'>\"+name+\"</td><td class=chamjo style='width:33%; text-align:center'>\"+si+\"</td><td class=chamjo style='width:36%; text-align:center'>\"+dept+\"</td></tr>\");\r\n");
      out.write("            \r\n");
      out.write("               \r\n");
      out.write("            }else{\r\n");
      out.write("               alert(\"원하는 사원을 선택하세요\")\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            });   \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            // 결재선 지정하는 펑션\r\n");
      out.write("            $(document).on(\"click\", \"#sangsin\", function(){ \r\n");
      out.write("               \r\n");
      out.write("               var name1 = $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(1)\").text();\r\n");
      out.write("               var name2 = $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(1)\").text();\r\n");
      out.write("               var name3 = $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(1)\").text();\r\n");
      out.write("               var name4 = $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(1)\").text();\r\n");
      out.write("               var name5 = $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(1)\").text();\r\n");
      out.write("               \r\n");
      out.write("               var position1 = $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(2)\").text();\r\n");
      out.write("               var position2 = $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(2)\").text();\r\n");
      out.write("               var position3 = $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(2)\").text();\r\n");
      out.write("               var position4 = $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(2)\").text();\r\n");
      out.write("               var position5 = $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(2)\").text();\r\n");
      out.write("               \r\n");
      out.write("               var dept1 = $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(3)\").text();\r\n");
      out.write("               var dept2 = $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(3)\").text();\r\n");
      out.write("               var dept3 = $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(3)\").text();\r\n");
      out.write("               var dept4 = $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(3)\").text();\r\n");
      out.write("               var dept5 = $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(3)\").text();\r\n");
      out.write("               \r\n");
      out.write("               var line1 = $(\"#applovalt\").find(\"tr:eq(2)\").find(\"td:eq(4)\").text();\r\n");
      out.write("               var line2 = $(\"#applovalt\").find(\"tr:eq(3)\").find(\"td:eq(4)\").text();\r\n");
      out.write("               var line3 = $(\"#applovalt\").find(\"tr:eq(4)\").find(\"td:eq(4)\").text();\r\n");
      out.write("               var line4 = $(\"#applovalt\").find(\"tr:eq(5)\").find(\"td:eq(4)\").text();\r\n");
      out.write("               var line5 = $(\"#applovalt\").find(\"tr:eq(6)\").find(\"td:eq(4)\").text();\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(1)\").find(\"td:eq(1)\").text(line1);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(2)\").find(\"td:eq(1)\").text(line2);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(3)\").find(\"td:eq(1)\").text(line3);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(4)\").find(\"td:eq(1)\").text(line4);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(5)\").find(\"td:eq(1)\").text(line5);\r\n");
      out.write("               \r\n");
      out.write("               if(name1 == \"-\") {\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(1)\").find(\"td:eq(2)\").text(name1);\r\n");
      out.write("               }else{\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(1)\").find(\"td:eq(2)\").text(name1 + \" \" + position1);\r\n");
      out.write("               }\r\n");
      out.write("               if(name2 == \"-\") {\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(2)\").find(\"td:eq(2)\").text(name2);\r\n");
      out.write("               }else{\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(2)\").find(\"td:eq(2)\").text(name2 + \" \" + position2);\r\n");
      out.write("               }\r\n");
      out.write("               if(name3 == \"-\") {\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(3)\").find(\"td:eq(2)\").text(name3);\r\n");
      out.write("               }else{\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(3)\").find(\"td:eq(2)\").text(name3 + \" \" + position3);\r\n");
      out.write("               }\r\n");
      out.write("               if(name4 == \"-\") {\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(4)\").find(\"td:eq(2)\").text(name4);\r\n");
      out.write("               }else{\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(4)\").find(\"td:eq(2)\").text(name4 + \" \" + position4);\r\n");
      out.write("               }\r\n");
      out.write("               if(name5 == \"-\") {\r\n");
      out.write("                  $(\"#table1\").find(\"tr:eq(5)\").find(\"td:eq(2)\").text(name5);\r\n");
      out.write("               }else{\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(5)\").find(\"td:eq(2)\").text(name5 + \" \" + position5);\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(1)\").find(\"td:eq(3)\").text(dept1);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(2)\").find(\"td:eq(3)\").text(dept2);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(3)\").find(\"td:eq(3)\").text(dept3);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(4)\").find(\"td:eq(3)\").text(dept4);\r\n");
      out.write("               $(\"#table1\").find(\"tr:eq(5)\").find(\"td:eq(3)\").text(dept5);\r\n");
      out.write("               \r\n");
      out.write("               var cham1 = \"\";\r\n");
      out.write("               for(var i=1; i<$(\"#t3\").find(\"tr\").length; i++) {\r\n");
      out.write("                  for(var ii=0; ii<$(\"#t3\").find(\"tr:eq(1)\").find(\"td\").length-1; ii++){ // 부서 삭제\r\n");
      out.write("                     cham1 += $(\"#t3\").find(\"tr:eq(\"+(i+1)+\")\").find(\"td:eq(\"+ii+\")\").text() + \" \";\r\n");
      out.write("                  }\r\n");
      out.write("                  if(i != $(\"#t3\").find(\"tr\").length-1){\r\n");
      out.write("                     cham1 += \", \";\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("               $(\"#cham1\").find(\"tr:eq(0)\").find(\"td:eq(0)\").text(cham1);\r\n");
      out.write("        \r\n");
      out.write("               $(\"#approval\").css({\"visibility\":\"hidden\"});\r\n");
      out.write("               $(\"#hide_div\").show();\r\n");
      out.write("                                                         \r\n");
      out.write("            }); // end of sangsin function\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("      }); // end of ready\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   </head>\r\n");
      out.write("   \r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("   \r\n");
      out.write("      input[type=\"button\"] {\r\n");
      out.write("         margin-top:7px;\r\n");
      out.write("         margin-right:10px;\r\n");
      out.write("         padding: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border: 2px solid white;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: gray;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("      #t2 {\r\n");
      out.write("         width: 170px;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("         background: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .white {\r\n");
      out.write("         background: #fff;\r\n");
      out.write("         height: 3px;\r\n");
      out.write("         font-size: 12px;\r\n");
      out.write("         width: 220px;\r\n");
      out.write("      }\r\n");
      out.write("      .font10 {\r\n");
      out.write("         font-size: 10px;\r\n");
      out.write("         width:33%;\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("      .font12 {\r\n");
      out.write("         font-size: 12px;\r\n");
      out.write("         width:300px;\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("      .font12_1 {\r\n");
      out.write("         font-size: 12px;\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .chamjo{\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("         \r\n");
      out.write("      .selec {\r\n");
      out.write("         background: #e2e2e2;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .sele {\r\n");
      out.write("         background: #e2e2e2;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .sel {\r\n");
      out.write("         background: #e2e2e2;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .abc {\r\n");
      out.write("         background: gray;\r\n");
      out.write("         padding: 0px;\r\n");
      out.write("         margin: 0px;\r\n");
      out.write("         border: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("/*       table { */\r\n");
      out.write("/*          border-top: 1px solid black; */\r\n");
      out.write("/*          border-bottom: 1px solid black; */\r\n");
      out.write("/*          border-collapse: collapse; */\r\n");
      out.write("/*       } */\r\n");
      out.write("      \r\n");
      out.write("      .right {\r\n");
      out.write("         float: right;\r\n");
      out.write("         margin-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("/*       td { */\r\n");
      out.write("/*          border: 1px solid #000; */\r\n");
      out.write("/*          text-align: center; */\r\n");
      out.write("/*          width: 120px; */\r\n");
      out.write("/*       } */\r\n");
      out.write("      \r\n");
      out.write("      .tdn {\r\n");
      out.write("         border: none;\r\n");
      out.write("         color: white;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .dd {\r\n");
      out.write("         background: #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .container {\r\n");
      out.write("         display: flex;\r\n");
      out.write("         width:1000px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .left-block {\r\n");
      out.write("         flex: 1;\r\n");
      out.write("         background: lightgray;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .right-block {\r\n");
      out.write("         flex: 3;\r\n");
      out.write("         margin-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      li {\r\n");
      out.write("         list-style: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .select {\r\n");
      out.write("         margin: 5px 5px;\r\n");
      out.write("         background: white;\r\n");
      out.write("         width: 100px;\r\n");
      out.write("         height: 28px;\r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .gu {\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         margin: auto;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .tbo {\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("            .td {\r\n");
      out.write("         border:1px solid #A4A4A4;\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("   </style>\r\n");
      out.write("   <body style=\"width:1000px;\">\r\n");
      out.write("      <div style=\"background-color: gray; height: 50px; width: 1000px; margin: 0px; padding: 0px; line-height:300%;\">\r\n");
      out.write("         <span style=\"font-size:25px; margin:20px; color:white;\"><strong>결재선 지정</strong></span>\r\n");
      out.write("       </div>\r\n");
      out.write("     <div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"left-block\" style=\"width: 100px;\">\r\n");
      out.write("            <aside class=\"side-bar\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <div style=\"border:1px solid gray; width:80%; margin-left:20px; background-color:white;\">\r\n");
      out.write("                  <div style=\"width:100%; background-color:gray; align:center; height:30px;\">\r\n");
      out.write("                     <span style=\"font-size:15px; color:white; line-height:200%; margin-left:10px;\">\r\n");
      out.write("                     <img src='resources/goats_icon/mem.png' style='width:15px; height:15px;'>&nbsp;조직도</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div style=\"background-color:white; width:80%;\">\r\n");
      out.write("                          <ul id=\"jojic\" style=\"padding-left:11px; margin-left:20px; background-color:white;\">\r\n");
      out.write("                         </ul>  \r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>      \r\n");
      out.write("                   <div style=\"border:1px solid gray; width:80%; margin-left:20px; background-color:white;\">\r\n");
      out.write("                  <div style=\"width:100%; background-color:gray; align:center; height:30px;\">\r\n");
      out.write("                     <span style=\"font-size:15px; color:white; line-height:200%; margin-left:10px;\">\r\n");
      out.write("                     <img src='resources/goats_icon/project_contractor.png' style='width:15px; height:15px;'>&nbsp;구성원</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div style=\"width:100%; height:225px; overflow: auto; border:none;\">\r\n");
      out.write("                        <table id=\"t2\" class=\"gu\" style=\" margin-left:0px; width:100%; border:1px solid lightgray;\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                           <td class='white' style=\"width:32%; border:1px solid white; color:white; background-color:#A4A4A4;\">이름 </td>\r\n");
      out.write("                           <td class='white' style=\"border:1px solid white; color:white; background-color:#A4A4A4;\">직책 </td>\r\n");
      out.write("                           <td class='white' style=\"width:40%; border:1px solid white; color:white; background-color:#A4A4A4;\">부서</td>\r\n");
      out.write("                       </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                     </div>\r\n");
      out.write("                   </div> \r\n");
      out.write("            </aside>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"mid-block\" style=\"margin:150px auto\">\r\n");
      out.write("            <input id=\"applober\" type=\"image\" src=\"resources/goats_icon/1.png\" style=\"width:100px; height:55px\"\r\n");
      out.write("               style=\"margin-top: 190px;\"><br> <br> <br> <br><br> <br> <br> <br>\r\n");
      out.write("            <input id=\"reference_btn\" type=\"image\" src=\"resources/goats_icon/4.png\" style=\"width:100px; height:55px\"\r\n");
      out.write("               style=\"margin-top: 100px;\"><br>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"right-block\">\r\n");
      out.write("            <br>\r\n");
      out.write("            <table id=\"applovalt\" class=\"tt\" style=\"width: 100%; text-align:center;\">\r\n");
      out.write("               <tr>\r\n");
      out.write("                    <th style=\"background-color:gray; border:none;\" colspan=\"2\">\r\n");
      out.write("                    <span style=\"color:white; font-size:20px;\">결재자</span>\r\n");
      out.write("                    </th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"tbo\">\r\n");
      out.write("                  <td class=\"td\" style=\"width:8%; background-color:#A4A4A4; border:1px solid white; border-left:1px solid #A4A4A4; color:white\">순서</td>\r\n");
      out.write("                  <td class=\"td\" style=\"width:23%; background-color:#A4A4A4; border:1px solid white; color:white\">이름</td>\r\n");
      out.write("                  <td class=\"td\" style=\"width:23%; background-color:#A4A4A4; border:1px solid white; color:white\">직책</td>\r\n");
      out.write("                  <td class=\"td\" style=\"width:23%; background-color:#A4A4A4; border:1px solid white; color:white\">부서</td>\r\n");
      out.write("                  <td class=\"td\" style=\"width:23%; background-color:#A4A4A4; border-left:1px solid white; border-top:1px solid white; border-bottom:1px solid white; border-rigth:1px solid #A4A4A4; color:white\">결재선</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"td ss\">\r\n");
      out.write("                  <td class=\"td\" style=\"color:white; background-color:#A4A4A4; border-bottom:1px solid white; border-right:1px solid white;\"><strong>1</strong></td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"td ss\">\r\n");
      out.write("                  <td class=\"td\" style=\"color:white; background-color:#A4A4A4; border-bottom:1px solid white; border-right:1px solid white;\"><strong>2</strong></td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"td ss\">\r\n");
      out.write("                  <td class=\"td\" style=\"color:white; background-color:#A4A4A4; border-bottom:1px solid white; border-right:1px solid white;\"><strong>3</strong></td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"td ss\">\r\n");
      out.write("                  <td class=\"td\" style=\"color:white; background-color:#A4A4A4; border-bottom:1px solid white; border-right:1px solid white;\"><strong>4</strong></td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"td ss\">\r\n");
      out.write("                  <td class=\"td\" style=\"color:white; background-color:#A4A4A4; border-right:1px solid white;\"><strong>5</strong></td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("                  <td class=\"td\">-</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <table class=\"tt\" style=\"width:100%; overflow: auto;\" id=\"t3\">            \r\n");
      out.write("               <tr>\r\n");
      out.write("                    <th style=\"background-color:gray; border:none; width:31%\">\r\n");
      out.write("                    <span style=\"color:white; font-size:20px;\">참조자</span>\r\n");
      out.write("                    </th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"dd\">\r\n");
      out.write("                  <td class=\"tdn\" align=\"center\" style=\"border:1px solid white; border-left:1px solid #A4A4A4;\">이름</td>\r\n");
      out.write("                  <td class=\"tdn\" align=\"center\" style=\"border:1px solid white; width:33%'\">직책</td>\r\n");
      out.write("                  <td class=\"tdn\" align=\"center\" style=\"border:1px solid white; width:36%; border-right:1px solid #A4A4A4;\">부서</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"background-color: gray; height: 50px; width: 1000px; margin: 0px; padding: 0px;\">         \r\n");
      out.write("         <input type=\"button\" class=\"right\" id=\"sangsin\" name=\"sangsin\" value=\"결재선 반영\">\r\n");
      out.write("         <input type=\"button\" class=\"right\" id=\"delbtn\" value=\"삭제\">\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
