/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-28 01:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.kos.employee.vo.GtEmployeeVO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/kosmo/Desktop/Legacy/el_project_legacy_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_goats/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688555200114L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.kos.employee.vo.GtEmployeeVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Object obj = request.getAttribute("gevo");
	GtEmployeeVO gevo = (GtEmployeeVO) obj;
	
	System.out.println("이메일 > :" + gevo.getGeemail());
	System.out.println("우편번호 > : " + gevo.getGezone());
	System.out.println("도로명주소 > :" + gevo.getGeroad());
	System.out.println("상세 > : " + gevo.getGeroaddetail());
	System.out.println("지번 > :" + gevo.getGejibun());
	System.out.println("전화번호 > :" + gevo.getGehp());
	
	String geemail = gevo.getGeemail();
	String gezone = gevo.getGezone();
	String geroad = gevo.getGeroad();
	String geroaddetail = gevo.getGeroaddetail();
	String gejibun = gevo.getGejibun();
	String gehp = gevo.getGehp();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>GOATS | MyPage</title>\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://webfontworld.github.io/kopus/KoPubWorldDotum.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"resources/css/mypage.css\">\r\n");
      out.write("	<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("	    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	    \r\n");
      out.write("	    <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				var geemail = \"");
      out.print(geemail);
      out.write("\";\r\n");
      out.write("				var gezone = \"");
      out.print(gezone);
      out.write("\";\r\n");
      out.write("				var geroad = \"");
      out.print(geroad);
      out.write("\";\r\n");
      out.write("				var geroaddetail = \"");
      out.print(geroaddetail);
      out.write("\";\r\n");
      out.write("				var gejibun = \"");
      out.print(gejibun);
      out.write("\";\r\n");
      out.write("				var gehp = \"");
      out.print(gehp);
      out.write("\";\r\n");
      out.write("	\r\n");
      out.write("				// 이메일 스플릿\r\n");
      out.write("				var email = geemail;\r\n");
      out.write("				var aaa = email.split(\"@\");\r\n");
      out.write("				console.log(aaa);\r\n");
      out.write("				console.log(aaa[0]);\r\n");
      out.write("				console.log(aaa[1]);\r\n");
      out.write("				console.log(typeof (aaa));\r\n");
      out.write("	\r\n");
      out.write("				//전화번호 스플릿\r\n");
      out.write("				var hp = gehp;\r\n");
      out.write("				var bbb = hp.split(\"-\");\r\n");
      out.write("				console.log(bbb);\r\n");
      out.write("				console.log(bbb[0]);\r\n");
      out.write("				console.log(bbb[1]);\r\n");
      out.write("				console.log(bbb[2]);\r\n");
      out.write("				console.log(typeof (bbb));\r\n");
      out.write("	\r\n");
      out.write("				$(\"#geemail0\").val(aaa[0]);\r\n");
      out.write("				$(\"#geemail1\").val(aaa[1]);\r\n");
      out.write("				$(\"#geemail2\").val(aaa[1]).prop(\"selected\", true);\r\n");
      out.write("				$(\"#gezone\").val(gezone);\r\n");
      out.write("				$(\"#geroad\").val(geroad);\r\n");
      out.write("				$(\"#geroaddetail\").val(geroaddetail);\r\n");
      out.write("				$(\"#gejibun\").val(gejibun);\r\n");
      out.write("				$(\"#gehp0\").val(bbb[0]).prop(\"selected\", true);\r\n");
      out.write("				$(\"#gehp1\").val(bbb[1]);\r\n");
      out.write("				$(\"#gehp2\").val(bbb[2]);\r\n");
      out.write("	\r\n");
      out.write("				$(\"#zonecode\").click(function() {\r\n");
      out.write("					new daum.Postcode({\r\n");
      out.write("						oncomplete : function(data) {\r\n");
      out.write("							$(\"#gezone\").val(data.zonecode);\r\n");
      out.write("							$(\"#geroad\").val(data.roadAddress);\r\n");
      out.write("							$(\"#gejibun\").val(data.jibunAddress);\r\n");
      out.write("						}\r\n");
      out.write("					}).open();\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				$('#geemail2').change(function(){\r\n");
      out.write("					$('#geemail2 option:selected').each(function(){\r\n");
      out.write("						if($(this).val() == '1'){\r\n");
      out.write("							var aa = $(\"#geemail1\").val();\r\n");
      out.write("							$(\"#geemail1\").val('');\r\n");
      out.write("							$(\"#geemail1\").attr(\"readonly\", false);\r\n");
      out.write("						}else{\r\n");
      out.write("							$(\"#geemail1\").val($(this).text());\r\n");
      out.write("							$(\"#geemail1\").attr(\"readonly\", true);\r\n");
      out.write("						}\r\n");
      out.write("					});	\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				$(document).on(\"click\", \"#infbtn\", function(){\r\n");
      out.write("	\r\n");
      out.write("					var gehp = $(\"#gehp0\").val() + \"-\" + $(\"#gehp1\").val() + \"-\" + $(\"#gehp2\").val(); \r\n");
      out.write("					var geemail = $(\"#geemail0\").val() + \"@\" + $(\"#geemail1\").val();\r\n");
      out.write("	\r\n");
      out.write("					$(\"#gehp\").val(gehp);\r\n");
      out.write("					$(\"#geemail\").val(geemail);\r\n");
      out.write("	\r\n");
      out.write("					let dataParam = $(\"#inf\").serialize();\r\n");
      out.write("	\r\n");
      out.write("					console.log(dataParam);\r\n");
      out.write("	\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"gtinfupdate.gos\",\r\n");
      out.write("						type : \"POST\",\r\n");
      out.write("						data : dataParam,	\r\n");
      out.write("						success : function(res){\r\n");
      out.write("						},\r\n");
      out.write("						error : function(e){\r\n");
      out.write("							console.log(e.responseText);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				var pw_nCnt = 0;\r\n");
      out.write("				var pwcheck = 0;\r\n");
      out.write("	\r\n");
      out.write("				// 확인\r\n");
      out.write("				$(document).on(\"click\", \"#pbtn\", function() {\r\n");
      out.write("	\r\n");
      out.write("					var mpw = $(\"#newpw\").val();\r\n");
      out.write("					var mpw_r = $(\"#newpwfirm\").val();\r\n");
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("					if (mpw == mpw_r) {\r\n");
      out.write("						pw_nCnt++;\r\n");
      out.write("					} else {\r\n");
      out.write("						$(\"#currenpw\").focus();\r\n");
      out.write("						$(\"#currenpw\").val(\"\");\r\n");
      out.write("						$(\"#newpw\").val(\"\");\r\n");
      out.write("						$(\"#newpwfirm\").val(\"\");\r\n");
      out.write("						alert(\"새 비밀번호와 새 비밀번호 확인이 일치하지 않습니다.\");\r\n");
      out.write("					}\r\n");
      out.write("	\r\n");
      out.write("					// currenpw 기존\r\n");
      out.write("					// newpw 새비밀\r\n");
      out.write("					// newpwfirm 새 확인\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("					if (pwcheck == 1) {\r\n");
      out.write("						$.ajax({\r\n");
      out.write("	\r\n");
      out.write("							url : \"gtpwCheck.gos\",\r\n");
      out.write("							type : \"POST\",\r\n");
      out.write("							async : false,\r\n");
      out.write("							data : {\r\n");
      out.write("								newpw : $(\"#newpw\").val(),\r\n");
      out.write("								currenpw : $(\"#currenpw\").val()\r\n");
      out.write("							},\r\n");
      out.write("							success : function(res) {\r\n");
      out.write("		/* 						if(\"gtpwCheck fail\" == res){\r\n");
      out.write("									alert(\"비밀번호를 정확하게 입력해 주세요.\");\r\n");
      out.write("								}else{\r\n");
      out.write("									alert(\"비밀번호가 변경 되었습니다.\");	\r\n");
      out.write("								} */\r\n");
      out.write("							},\r\n");
      out.write("							error : function(e) {}\r\n");
      out.write("						});\r\n");
      out.write("	\r\n");
      out.write("					} else {\r\n");
      out.write("	\r\n");
      out.write("						$(\"#newpwfirm\").val(\"\");\r\n");
      out.write("						$(\"#newpw\").focus();\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				$(\"#newpw\").keyup(function() {\r\n");
      out.write("	\r\n");
      out.write("					var pwnew = $(\"#newpw\").val();\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"gtpwupdateCheck.gos\",\r\n");
      out.write("						type : \"POST\",\r\n");
      out.write("						data : {\r\n");
      out.write("							newpw : pwnew\r\n");
      out.write("						},\r\n");
      out.write("						success : function(res) {\r\n");
      out.write("						console.log(res);\r\n");
      out.write("\r\n");
      out.write("							if (res == \"true+true+true+true+true\") {\r\n");
      out.write("		\r\n");
      out.write("								pwcheck++;\r\n");
      out.write("														\r\n");
      out.write("							}\r\n");
      out.write("						},\r\n");
      out.write("						error : function(e) {\r\n");
      out.write("							console.log(e.responseText);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		</script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $('.rightTop button').click(function(){\r\n");
      out.write("                console.log(\"dd\")\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            // rightMyInfo\r\n");
      out.write("            // rightPassChange\r\n");
      out.write("            // passBtn\r\n");
      out.write("            // myInfoBtn\r\n");
      out.write("            $('.myInfoBtn').click(function(){\r\n");
      out.write("                $(this).addClass('on');\r\n");
      out.write("                $('.rightPassChange').addClass('none');\r\n");
      out.write("                $('.rightMyInfo').removeClass('none');\r\n");
      out.write("                $('.passBtn').removeClass('on')\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            $('.passBtn').click(function(){\r\n");
      out.write("                $(this).addClass('on');\r\n");
      out.write("                $('.rightPassChange').removeClass('none');\r\n");
      out.write("                $('.rightMyInfo').addClass('none');\r\n");
      out.write("                $('.myInfoBtn').removeClass('on')\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("<style class=\"goatsfont\">\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'KoPubWorldDotum';\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"container2\" style=\"margin: 0\">\r\n");
      out.write("      <!--  사이드바 -->\r\n");
      out.write("      <div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/mainSide-bar.jsp", out, false);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 탑바 -->\r\n");
      out.write("      <div style=\"margin: 0; padding: 0; width:100%\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/Top-bar.jsp", out, false);
      out.write("\r\n");
      out.write("      <div class=\"container\" id=\"rightcon\">\r\n");
      out.write("        \r\n");
      out.write("		<!--  -->\r\n");
      out.write("        <div class=\"myPageWrap\">\r\n");
      out.write("            <h2>마이페이지</h2>\r\n");
      out.write("            <div class=\"myPageContentWrap\">\r\n");
      out.write("                <!-- 왼쪽 프로필 사진있는곳 -->\r\n");
      out.write("                <div class=\"myPageContentLeft\">\r\n");
      out.write("                    <div class=\"leftTop\">\r\n");
      out.write("                        <div class=\"leftImage\" style=\"background-image: url('resources/goats_icon/person2.png');\"></div>\r\n");
      out.write("                        <div>이름 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gevo.gename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                        <div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gevo.gedept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"leftBottom\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>직급</span>\r\n");
      out.write("                            <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gevo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>이메일</span>\r\n");
      out.write("                            <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gevo.geemail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>입사일</span>\r\n");
      out.write("                            <span>\r\n");
      out.write("                            	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     			");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(insertdate,0,10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /왼쪽 프로필 사진있는곳 -->\r\n");
      out.write("\r\n");
      out.write("                <!-- 오른쪽 내정보랑 비번변경 -->\r\n");
      out.write("	                <div class=\"myPageContentRight\">\r\n");
      out.write("	                    <div class=\"rightTop\">\r\n");
      out.write("	                        <button class=\"myInfoBtn on\">내 정보</button>\r\n");
      out.write("	                        <button class=\"passBtn\">비밀번호 변경</button>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"rightBottom\">\r\n");
      out.write("	                        <!-- 내 정보 -->\r\n");
      out.write("	                        <div>\r\n");
      out.write("	                        	<form id=\"inf\" class=\"rightMyInfo\">\r\n");
      out.write("		                            <div>\r\n");
      out.write("		                                <div>Email</div>\r\n");
      out.write("		                                <input type=\"text\" name=\"geemail0\" id=\"geemail0\" style=\"width: 100px\">  @ \r\n");
      out.write("		                                <input type=\"text\"name=\"geemail1\" id=\"geemail1\" style=\"width: 100px\"placeholder=\"직접입력\">\r\n");
      out.write("		                            </div>\r\n");
      out.write("		                            <div>\r\n");
      out.write("		                                <div>주소</div>\r\n");
      out.write("		                                <input type=\"text\" name=\"gezone\" id=\"gezone\" placeholder=\"우편번호\">\r\n");
      out.write("										<input type=\"button\" name=\"zonecode\" id=\"zonecode\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("										\r\n");
      out.write("		                            </div>\r\n");
      out.write("		                            <div>\r\n");
      out.write("		                            	<div></div>\r\n");
      out.write("										<input type=\"text\" name=\"geroad\" id=\"geroad\" placeholder=\"도로명주소\"> \r\n");
      out.write("										<input type=\"text\" name=\"geroaddetail\" id=\"geroaddetail\" placeholder=\"도로명주소 상세주소\">\r\n");
      out.write("										<input type=\"text\" name=\"gejibun\" id=\"gejibun\" placeholder=\"지번주소\">\r\n");
      out.write("		                           	</div>\r\n");
      out.write("		                            <div>\r\n");
      out.write("		                                <div>전화번호</div>\r\n");
      out.write("		                                <select name=\"gehp0\" id=\"gehp0\">\r\n");
      out.write("											<option value=\"010\">010</option>\r\n");
      out.write("											<option value=\"011\">011</option>\r\n");
      out.write("											<option value=\"016\">016</option>\r\n");
      out.write("										</select> - <input type=\"text\" name=\"gehp1\" id=\"gehp1\" size=\"2\" maxlength=\"4\"> - <input type=\"text\" name=\"gehp2\" id=\"gehp2\" size=\"2\" maxlength=\"4\">\r\n");
      out.write("		                            </div>\r\n");
      out.write("		                            <div>\r\n");
      out.write("		                                <div></div>                      \r\n");
      out.write("		                               <input style=\"width:114.3px;\" type=\"button\" value=\"저장\" id=\"infbtn\" class=\"registerBtn\">\r\n");
      out.write("		                            </div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input type=\"hidden\" id=\"gehp\" name=\"gehp\" value=\"\"> \r\n");
      out.write("										<input type=\"hidden\" id=\"geemail\" name=\"geemail\" value=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("	                            </form>\r\n");
      out.write("	                        </div>\r\n");
      out.write("                        <!-- 내 정보 -->\r\n");
      out.write("                        <!-- 비밀번호 수정 -->\r\n");
      out.write("                        <div class=\"rightPassChange none\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>기존 비밀번호</div>\r\n");
      out.write("								<input type=\"password\" id=\"currenpw\" name=\"gepw\" value=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>새 비밀번호</div>\r\n");
      out.write("                                <input type=\"password\" id=\"newpw\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>새 비밀번호 확인</div>\r\n");
      out.write("                                <input type=\"password\" id=\"newpwfirm\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div></div>\r\n");
      out.write("                                <p class=\"rightPassP\">최소 8개의 숫자와 소문자, 대문자, 특수기호를 입력해주세요.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div></div>\r\n");
      out.write("                                <input type=\"button\" value=\"저장\" id=\"pbtn\" class=\"registerBtn\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 비밀번호 수정 -->\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 오른쪽 내정보랑 비번변경 -->\r\n");
      out.write("            	</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("       		</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/mypage/mypage.jsp(271,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("insertdate");
      // /WEB-INF/views/mypage/mypage.jsp(271,29) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/mypage.jsp(271,29) '${gevo.insertdate}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${gevo.insertdate}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
