/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-08-02 07:51:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.draft;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public final class draftInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8");
      out.write('\r');
      out.write('\n');

   Logger log = LogManager.getLogger(this.getClass());
   Date now = new Date();
   SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy년 MM월 dd일");
   String currentDate = dateFormat.format(now);
   String gsname = (String) request.getAttribute("gsname");
   String genum = (String) request.getAttribute("genum");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("      <title>Insert title here</title>\r\n");
      out.write("          <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("          <link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("          <script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("          <style type=\"text/css\">\r\n");
      out.write("          .left-align {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            }\r\n");
      out.write("            .button-container {\r\n");
      out.write("               text-align: right;\r\n");
      out.write("             }          \r\n");
      out.write("             .initial-size {\r\n");
      out.write("                 min-height: 200px; \r\n");
      out.write("                 width : 1000px;\r\n");
      out.write("             }\r\n");
      out.write("            th {\r\n");
      out.write("                    background-color: #f2f2f2;\r\n");
      out.write("                 }\r\n");
      out.write("               table {\r\n");
      out.write("                  border-collapse: collapse;\r\n");
      out.write("                  width: 1000px;\r\n");
      out.write("                }\r\n");
      out.write("              th, td {\r\n");
      out.write("                  border: 1px solid black;\r\n");
      out.write("                  padding: 8px;\r\n");
      out.write("                  align: left;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("      #approval{\r\n");
      out.write("                 visibility: hidden;\r\n");
      out.write("                 position: absolute;\r\n");
      out.write("                 background-color:#fff;\r\n");
      out.write("                 width:100%;\r\n");
      out.write("                 height:100%;\r\n");
      out.write("                 margin:auto;\r\n");
      out.write("           }\r\n");
      out.write("      </style>\r\n");
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      \r\n");
      out.write("          var currentDate = new Date();\r\n");
      out.write("          var formattedDate = currentDate.getFullYear() + '년 ' + (currentDate.getMonth() + 1) + '월 ' + currentDate.getDate() + '일';\r\n");
      out.write("      \r\n");
      out.write("         $(document).ready(function(){\r\n");
      out.write("            \r\n");
      out.write("            var gsname = \"");
      out.print(gsname);
      out.write("\";\r\n");
      out.write("            $(\"#gsname1\").val(gsname);\r\n");
      out.write("            \r\n");
      out.write("            var genum = \"");
      out.print(genum);
      out.write("\";\r\n");
      out.write("            $(\"#genum1\").val(genum);\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("            url : \"DraftChanbun.gos\",\r\n");
      out.write("            success:function(res){\r\n");
      out.write("\r\n");
      out.write("               var gdrnum = res;\r\n");
      out.write("                                   \r\n");
      out.write("               $(\"#gdrnum1\").text(gdrnum);\r\n");
      out.write("               $(\"#gdrnum\").val(gdrnum);\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            error:function(e){\r\n");
      out.write("               console.log(e.responseText)\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("         });\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \"#gdrsign\", function(){\r\n");
      out.write("               \r\n");
      out.write("               if($(this).prop('checked')){          \r\n");
      out.write("                  //$('input[type=\"checkbox\"][name=\"mnum\"]').prop('checked',false);\r\n");
      out.write("                  $('.gdrsign').prop('checked',false);\r\n");
      out.write("                  $(this).prop('checked',true);\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \"#gdrcontract\", function(){\r\n");
      out.write("               \r\n");
      out.write("               if($(this).prop('checked')){\r\n");
      out.write("                  //$('input[type=\"checkbox\"][name=\"mnum\"]').prop('checked',false);\r\n");
      out.write("                  $('.gdrcontract').prop('checked',false);\r\n");
      out.write("                  $(this).prop('checked',true);\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(document).on(\"click\", \"#sbtn\", function(){\r\n");
      out.write("                         \r\n");
      out.write("                 var hu1 = $(\"#hu1\").text()\r\n");
      out.write("              var hu2 = $(\"#hu2\").text()\r\n");
      out.write("              var hu3 = $(\"#hu3\").text()\r\n");
      out.write("              var hu4 = $(\"#hu4\").text()\r\n");
      out.write("              var hu5 = $(\"#hu5\").text()\r\n");
      out.write("              \r\n");
      out.write("              var reference1 = $(\"#reference1\").text();\r\n");
      out.write("             \r\n");
      out.write("              $(\"#hu1_1\").val(hu1);\r\n");
      out.write("              $(\"#hu1_2\").val(hu2);\r\n");
      out.write("              $(\"#hu1_3\").val(hu3);\r\n");
      out.write("              $(\"#hu1_4\").val(hu4);\r\n");
      out.write("              $(\"#hu1_5\").val(hu5);\r\n");
      out.write("\r\n");
      out.write("              var du1 = $(\"#du1\").text()\r\n");
      out.write("              var du2 = $(\"#du2\").text()\r\n");
      out.write("              var du3 = $(\"#du3\").text()\r\n");
      out.write("              var du4 = $(\"#du4\").text()\r\n");
      out.write("              var du5 = $(\"#du5\").text()\r\n");
      out.write("              \r\n");
      out.write("               $(\"#du1_1\").val(du1);\r\n");
      out.write("              $(\"#du1_2\").val(du2);\r\n");
      out.write("              $(\"#du1_3\").val(du3);\r\n");
      out.write("              $(\"#du1_4\").val(du4);\r\n");
      out.write("              $(\"#du1_5\").val(du5);\r\n");
      out.write("   \r\n");
      out.write("              $(\"#writer\").val(gsname);\r\n");
      out.write("              $(\"#genum\").val(genum);       \r\n");
      out.write("              $(\"#reference\").val(reference1);\r\n");
      out.write("              \r\n");
      out.write("                var a = $('.ql-editor').html();   \r\n");
      out.write("                var b =$(\"#quill_html\").val(a);\r\n");
      out.write("                  \r\n");
      out.write("                var cc = $(\"#cham1\").find(\"tr:eq(0)\").find(\"td:eq(0)\").text();\r\n");
      out.write("                 var aa = cc.replaceAll(\", \", \",\");\r\n");
      out.write("                  \r\n");
      out.write("              $(\"#gdrapprover\").val(aa);\r\n");
      out.write("                \r\n");
      out.write("                 let dataParam = $(\"#draftFormAll\").serialize();\r\n");
      out.write("                 \r\n");
      out.write("                 $.ajax({\r\n");
      out.write("                  url : \"draftInsert.gos\",\r\n");
      out.write("                  data : dataParam,\r\n");
      out.write("                  success : function(res){\r\n");
      out.write("                     if(res == \"OK\"){\r\n");
      out.write("                         $(\"#gdr_file_form\").attr({\r\n");
      out.write("                            \"action\" : \"draftInsertFile.gos\",\r\n");
      out.write("                            \"method\" : \"POST\",\r\n");
      out.write("                            \"enctype\":\"multipart/form-data\"\r\n");
      out.write("                         }).submit();\r\n");
      out.write("                     }else{\r\n");
      out.write("                        alert(\"입력 실패\");\r\n");
      out.write("                     }\r\n");
      out.write("                  },\r\n");
      out.write("                  error : function(e){\r\n");
      out.write("                     console.log(e.responseText);\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("               \r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("           $(document).on(\"click\", \"#gbtn\", function(){\r\n");
      out.write("            $(\"#approval\").css({\"visibility\":\"visible\"});\r\n");
      out.write("            $(\"#hide_div\").hide();\r\n");
      out.write("         });\r\n");
      out.write("            \r\n");
      out.write("         });\r\n");
      out.write("      \r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("   </head>\r\n");
      out.write("\r\n");
      out.write("   <body>\r\n");
      out.write("     <div id=\"approval\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../approvalline/select.jsp", out, false);
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("     <div id=\"hide_div\">\r\n");
      out.write("        <form name=\"draftFormAll\" id=\"draftFormAll\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <input type=\"hidden\" id=\"gdrapprover\" name=\"gdrapprover\" value=\"\">\r\n");
      out.write("         <input type=\"hidden\" id=\"gdrdept\" name=\"gdrdept\" value=\"\">\r\n");
      out.write("     </div>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("         <button type=\"button\" id=\"gbtn\">결재선지정</button>\r\n");
      out.write("         <button type=\"button\" id=\"sbtn\">상신</button>\r\n");
      out.write("         <button type=\"button\" id=\"cbtn\">취소</button>\r\n");
      out.write("        </div>\r\n");
      out.write("     \r\n");
      out.write("     <h2 align=\"center\">기안서(일반)</h2>\r\n");
      out.write("     <br>\r\n");
      out.write("     <table style=\"text-align:center\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"120px\">문서번호</th><td width=\"230px\" id=\"gdrnum1\"></td>\r\n");
      out.write("           <th width=\"120px\">보안구분</th><td width=\"230px\">비공개</td>\r\n");
      out.write("            <th width=\"120px\">보존연한</th><td width=\"230px\">5년</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"10%\">작성자</th><td width=\"23%\" id=\"gsname1\">");
      out.print(gsname);
      out.write("</td>\r\n");
      out.write("            <th width=\"10%\">작성일자</th><td colspan=\"3\">");
      out.print( currentDate );
      out.write("</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <table style=\"text-align:center\" id=\"table1\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"5%\">순서</th>\r\n");
      out.write("            <th width=\"8%\">구분</th>\r\n");
      out.write("            <th width=\"17%\">결재자</th>\r\n");
      out.write("            <th width=\"17%\">부서</th>\r\n");
      out.write("            <th width=\"8%\">상태</th>\r\n");
      out.write("            <th width=\"10%\">결재일</th>\r\n");
      out.write("            <th width=\"35%\">결재의견</th>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>1</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td id=\"hu1\"></td>\r\n");
      out.write("            <td id=\"du1\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>2</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td id=\"hu2\"></td>\r\n");
      out.write("            <td id=\"du2\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>3</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td id=\"hu3\"></td>\r\n");
      out.write("            <td id=\"du3\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>4</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td id=\"hu4\"></td>\r\n");
      out.write("            <td id=\"du4\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>5</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td id=\"hu5\"></td>\r\n");
      out.write("            <td id=\"du5\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            \r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <table id=\"cham1\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"17%\">참　　조</th>\r\n");
      out.write("            <td id=\"reference1\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <table>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"17%\">제　　목</th>\r\n");
      out.write("            <td><input type=\"text\" name=\"gdrsubject\" id=\"gdrsubject\" size=\"112px\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div style=\"align:left\">\r\n");
      out.write("      <table>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"17%\">대표이사 등의 사안</th>\r\n");
      out.write("            <td class=\"left-align\"><input type=\"checkbox\" class=\"gdrsign\" name=\"gdrsign\" id=\"gdrsign\" value=\"0\" checked/>사용인감 날인\r\n");
      out.write("                          <input type=\"checkbox\" class=\"gdrsign\" name=\"gdrsign\" id=\"gdrsign\" value=\"1\"/>법인인감 날인\r\n");
      out.write("                          </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th width=\"17%\">계 약 형 태</th>\r\n");
      out.write("            <td class=\"left-align\"><input type=\"checkbox\" class=\"gdrcontract\" name=\"gdrcontract\" id=\"gdrcontract\" value=\"0\">구매\r\n");
      out.write("                          <input type=\"checkbox\" class=\"gdrcontract\" name=\"gdrcontract\" id=\"gdrcontract\" value=\"1\">계약\r\n");
      out.write("                          <input type=\"checkbox\" class=\"gdrcontract\" name=\"gdrcontract\" id=\"gdrcontract\" value=\"2\">매출\r\n");
      out.write("                          <input type=\"checkbox\" class=\"gdrcontract\" name=\"gdrcontract\" id=\"gdrcontract\" value=\"3\">입찰\r\n");
      out.write("                          </td>\r\n");
      out.write("      </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <div id=\"editor\" class=\"initial-size\"></div>\r\n");
      out.write("    <input type=\"hidden\" id=\"quill_html\" name=\"gdrmemo\">\r\n");
      out.write("    <script>\r\n");
      out.write("      \r\n");
      out.write("        var quill = new Quill('#editor', {\r\n");
      out.write("         // Quill 설정 옵션\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("       // 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("       var editorContainer = document.querySelector('#editor');\r\n");
      out.write("       editorContainer.addEventListener('click', function() {\r\n");
      out.write("         quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("       });\r\n");
      out.write("    \r\n");
      out.write("        var toolbarOptions = [\r\n");
      out.write("            ['bold', 'italic', 'underline', 'strike'],\r\n");
      out.write("            ['link', 'image'],\r\n");
      out.write("            [{ 'list': 'ordered' }, { 'list': 'bullet' }],\r\n");
      out.write("            [{ 'header': [1, 2] }]\r\n");
      out.write("        ];\r\n");
      out.write("      \r\n");
      out.write("        var quill = new Quill('#editor', {\r\n");
      out.write("            modules: {\r\n");
      out.write("                toolbar: toolbarOptions\r\n");
      out.write("            },\r\n");
      out.write("            theme: 'snow'\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function myFunction(){\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    <div>\r\n");
      out.write("    <input type=\"hidden\" id=\"gdrnum\" name=\"gdrnum\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"writer\" name=\"writer\">\r\n");
      out.write("    <input type=\"hidden\" id=\"reference\" name=\"reference\" value=\"\">    \r\n");
      out.write("    <input type=\"hidden\" id=\"hu1_1\" name=\"gdrapprover1\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"du1_1\" name=\"gdrdept1\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"hu1_2\" name=\"gdrapprover2\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"du1_2\" name=\"gdrdept2\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"hu1_3\" name=\"gdrapprover3\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"du1_3\" name=\"gdrdept3\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"hu1_4\" name=\"gdrapprover4\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"du1_4\" name=\"gdrdept4\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"hu1_5\" name=\"gdrapprover5\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"du1_5\" name=\"gdrdept5\" value=\"\">\r\n");
      out.write("    <input type=\"hidden\" id=\"genum1\" name=\"genum\">\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <br>\r\n");
      out.write("   <form id=\"gdr_file_form\">\r\n");
      out.write("   <table>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th width=\"17%\">첨 부 파 일</th>\r\n");
      out.write("            <td class=\"left-align\"><input type=\"file\" name=\"gdrfile\" id=\"gdrfile\" multiple=\"multiple\"></td><!-- 파일 -->\r\n");
      out.write("      </tr>            \r\n");
      out.write("   </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div class=\"button-container\">\r\n");
      out.write("         <button type=\"button\" id=\"gbtn\">결재선지정</button>\r\n");
      out.write("         <button type=\"button\" id=\"sbtn\">상신</button>\r\n");
      out.write("         <button type=\"button\" id=\"cbtn\">취소</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
