/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-26 04:59:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.draft;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.common.DateFormatUtil;
import com.gt.s.kos.draft.vo.GtDraftVO;
import com.gt.s.common.CodeUtil;

public final class draftSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.common.DateFormatUtil");
    _jspx_imports_classes.add("com.gt.s.kos.draft.vo.GtDraftVO");
    _jspx_imports_classes.add("com.gt.s.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');

	GtDraftVO gvo = (GtDraftVO) request.getAttribute("gdvo");
String app = gvo.getApprover();
String count = gvo.getCount();
String s = CodeUtil.edsmjeoncheck(app, Integer.parseInt(count));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".left-align {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container {\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#approvalline {\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      \r\n");
      out.write("         $(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				var gdrsubject = '");
      out.print(gvo.getGdrsubject());
      out.write("';\r\n");
      out.write("				var gdrmemo = '");
      out.print(gvo.getGdrmemo());
      out.write("';\r\n");
      out.write("				var gdrsign = '");
      out.print(gvo.getGdrsign());
      out.write("';\r\n");
      out.write("				var gdrcontract = '");
      out.print(gvo.getGdrcontract());
      out.write("';\r\n");
      out.write("				var genum = '");
      out.print(gvo.getGenum());
      out.write("';\r\n");
      out.write("				var writer = '");
      out.print(gvo.getWriter());
      out.write("';\r\n");
      out.write("				var reference = '");
      out.print(gvo.getReference());
      out.write("';\r\n");
      out.write("				var approver = '");
      out.print(gvo.getApprover());
      out.write("';\r\n");
      out.write("				var dept = '");
      out.print(gvo.getDept());
      out.write("';\r\n");
      out.write("				var pro = '");
      out.print(gvo.getProval());
      out.write("';\r\n");
      out.write("				var appcount = '");
      out.print(gvo.getCount());
      out.write("';\r\n");
      out.write("				var gdrsign = '");
      out.print( gvo.getGdrsign() );
      out.write("';\r\n");
      out.write("				var gdrcontract = '");
      out.print( gvo.getGdrcontract() );
      out.write("';\r\n");
      out.write("				\r\n");
      out.write("				if(gdrsign = '0') {\r\n");
      out.write("					gdrsign = \"사용인감 날인\";\r\n");
      out.write("				}else{\r\n");
      out.write("					gdrsign = \"법인인감 날인\";\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$(\"#gdrsign\").text(gdrsign);\r\n");
      out.write("				\r\n");
      out.write("				if(gdrcontract = '0'){\r\n");
      out.write("					gdrcontract = \"구매\";\r\n");
      out.write("				} else if(gdrcontract = '1'){\r\n");
      out.write("					gdrcontract = \"계약\";\r\n");
      out.write("				} else if(gdrcontract = '2'){\r\n");
      out.write("					gdrcontract = \"매출\";\r\n");
      out.write("				} else if(gdrcontract = '3'){\r\n");
      out.write("					gdrcontract = \"입찰\";\r\n");
      out.write("				}\r\n");
      out.write("			\r\n");
      out.write("				$(\"#gdrcontract\").text(gdrcontract);\r\n");
      out.write("					\r\n");
      out.write("				var s = '");
      out.print(s);
      out.write("';\r\n");
      out.write("				var app_ = approver.split(\"/\");\r\n");
      out.write("				var dept_ = dept.split(\"/\");\r\n");
      out.write("\r\n");
      out.write("				if (pro != 'null') {\r\n");
      out.write("					var pro_ = pro.split(\"/\");\r\n");
      out.write("				} else {\r\n");
      out.write("					var pro_ = \"\";\r\n");
      out.write("				}\r\n");
      out.write("				console.log(\"s > : \" + s);\r\n");
      out.write("				if (appcount < 0) {\r\n");
      out.write("					var nappcount = Number(appcount) + 10;\r\n");
      out.write("					for (var i = 0; i < app_.length; i++) {\r\n");
      out.write("						if (app_[i] != \"-\") {\r\n");
      out.write("							if (app_[i] != \"-\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("								if ($(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("									$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("											.find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("							if (nappcount == i) {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("								if ($(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("									$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("											.find(\"td:eq(4)\").text(\"반려\");\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				} else {\r\n");
      out.write("					if (s != '') {\r\n");
      out.write("						for (var i = 0; i < app_.length; i++) {\r\n");
      out.write("							if (app_[i] != \"-\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("								$(\"#table1\").find(\r\n");
      out.write("										\"tr:eq(\" + (appcount - 9) + \")\").find(\r\n");
      out.write("										\"td:eq(5)\").text(pro_[0]);\r\n");
      out.write("								if ($(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("									$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("											.find(\"td:eq(4)\").text(\"전결\");\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					} else {\r\n");
      out.write("						for (var i = 0; i < app_.length; i++) {\r\n");
      out.write("							if (app_[i] != \"-\") {\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(1)\").text(\"결재\");\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(2)\").text(app_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(3)\").text(dept_[i]);\r\n");
      out.write("								$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text(pro_[i]);\r\n");
      out.write("								if ($(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("										.find(\"td:eq(5)\").text() != \"\") {\r\n");
      out.write("									$(\"#table1\").find(\"tr:eq(\" + (i + 1) + \")\")\r\n");
      out.write("											.find(\"td:eq(4)\").text(\"결재완료\");\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				var num = '");
      out.print( gvo.getGdrnum() );
      out.write("';\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"fileDownloadlistdr.gos\",\r\n");
      out.write("					type:\"GET\",\r\n");
      out.write("					data:{\"gdrnum\":num},\r\n");
      out.write("					success:whens\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				function whens(d) {\r\n");
      out.write("					var filename = d.split(\",\");\r\n");
      out.write("					for(var i=0; i<filename.length-1; i++) {\r\n");
      out.write("						$(\"#gdr_file_form\").find(\"tr:eq(0)\").find(\"td:eq(0)\").append(\"<a href='fileDownloaddr?file=\"+filename[i]+\"&num=\"+num+\"' target='_blank'>\"+filename[i]+\"</a><br>\");\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}		\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("	// 				$.ajax({\r\n");
      out.write("	// 					url:\"fileDownloadlist.gos\",\r\n");
      out.write("	// 					type:\"GET\",\r\n");
      out.write("	// 					data:{\"gsnum\":num},\r\n");
      out.write("	// 					success:whens\r\n");
      out.write("	// 				});\r\n");
      out.write("\r\n");
      out.write("	// 				function whens(d) {\r\n");
      out.write("	// 					var filename = d.split(\",\");\r\n");
      out.write("	// 					for(var i=0; i<filename.length-1; i++) {\r\n");
      out.write("	// 						$(\"#table3\").find(\"tr:eq(0)\").find(\"td:eq(0)\").append(\"<a href='fileDownload?file=\"+filename[i]+\"&num=\"+num+\"' target='_blank'>\"+filename[i]+\"</a><br>\");\r\n");
      out.write("\r\n");
      out.write("	// 					}\r\n");
      out.write("	// 				}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form name=\"draftFormAll\" id=\"draftFormAll\">\r\n");
      out.write("\r\n");
      out.write("		<h2 align=\"center\">기안서(일반)</h2>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table style=\"text-align: center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"120px\">문서번호</th>\r\n");
      out.write("				<td width=\"230px\">");
      out.print(gvo.getGdrnum());
      out.write("</td>\r\n");
      out.write("				<th width=\"120px\">보안구분</th>\r\n");
      out.write("				<td width=\"230px\">비공개</td>\r\n");
      out.write("				<th width=\"120px\">보존연한</th>\r\n");
      out.write("				<td width=\"230px\">5년</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"10%\">작성자</th>\r\n");
      out.write("				<td width=\"23%\">");
      out.print(gvo.getWriter());
      out.write("</td>\r\n");
      out.write("				<th width=\"10%\">작성일자</th>\r\n");
      out.write("				<td colspan=\"3\">");
      out.print(gvo.getInsertdate());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table style=\"text-align: center\" id=\"table1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"5%\">순서</th>\r\n");
      out.write("				<th width=\"8%\">구분</th>\r\n");
      out.write("				<th width=\"17%\">결재자</th>\r\n");
      out.write("				<th width=\"17%\">부서</th>\r\n");
      out.write("				<th width=\"8%\">상태</th>\r\n");
      out.write("				<th width=\"10%\">결재일</th>\r\n");
      out.write("				<th width=\"35%\">결재의견</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">1</td>\r\n");
      out.write("				<td id=\"snag1\"></td>\r\n");
      out.write("				<td id=\"hu1\" class=\"approver\"></td>\r\n");
      out.write("				<td id=\"dept1\" class=\"dept\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>2</td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td id=\"hu2\"></td>\r\n");
      out.write("				<td id=\"du2\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>3</td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td id=\"hu3\"></td>\r\n");
      out.write("				<td id=\"du3\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>4</td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td id=\"hu4\"></td>\r\n");
      out.write("				<td id=\"du4\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>5</td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td id=\"hu5\"></td>\r\n");
      out.write("				<td id=\"du5\"></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("            	");
 if(gvo.getReference() == null) {
            		gvo.setReference(" ");
            } 
      out.write("\r\n");
      out.write("				<th width=\"17%\">참 조</th>\r\n");
      out.write("				<td>");
      out.print(gvo.getReference());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"17%\">제 목</th>\r\n");
      out.write("				<td>");
      out.print(gvo.getGdrsubject());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div style=\"align: left\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"17%\">대표이사 등의 사안</th>\r\n");
      out.write("					<td class=\"left-align\" id=\"gdrsign\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"17%\">계 약 형 태</th>\r\n");
      out.write("					<td class=\"left-align\" id=\"gdrcontract\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"300px;\">");
      out.print(gvo.getGdrmemo());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<form id=\"gdr_file_form\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"17%\">첨 부 파 일</th>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<!-- 파일 -->\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
